### ISSUE TITLE
Script does not trigger If you goto Anime page from History

### ISSUE THREAD

**Issue by Adyel** [lolamtisch/MALSync#1]
If you got to an anime from `Profile > Anime History` and Click on any anime from there the script won't work. 
![screenshot at 2018-10-04 12-47-43](https://user-images.githubusercontent.com/4653623/46457425-1ee33100-c7d4-11e8-8961-6e56ea0dbb4c.png)

It's because the routing is different (The PHP  one).
![image](https://user-images.githubusercontent.com/4653623/46457461-40dcb380-c7d4-11e8-8deb-bfb7660d5a2d.png)

As you are matching the `*://myanimelist.net/anime/*` it won't work.

We might need to add and change related functions.
```js
@include     /^https?:\/\/myanimelist.net\/((anime(list)?|manga(list)?)(\.php\?.*id=|\/)|character|people|search)/
```

I still don't know much about JS/TS otherwise I would have made a pull myself.

**Comment by lolamtisch** [comment]
Already forgot about that.
Fixed in bfdf095d93e237bff9bade27c1d294a14fc8a0b0, will be in the next release.
