### ISSUE TITLE
Implementing "CTRL + M" as a shortcut for miniMAL

### ISSUE THREAD

**Issue by AccelerateIzaya** [lolamtisch/MALSync#12]
I'd love if this shortcut is implemented in the extension like it was in the script. :D

**Comment by Eskander** [comment]
<kbd>Ctrl</kbd>+<kbd>M</kbd> in Firefox is used to mute tab.  You should probably pick another keyboard shortcut.

**Comment by lolamtisch** [comment]
<kbd>Alt</kbd>+<kbd>M</kbd> looks save according to [Firefox](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly?redirectlocale=en-US&redirectslug=Keyboard%20shortcuts) and [Chrome](https://support.google.com/chrome/answer/157179?hl=en)

**Comment by stapuft** [comment]
as an addendum to this request, would it be possible to add other keyboard shortcuts? 9anime has a good keyboard integration so i would suggest it as a starting point. here is my exact idea, based on their controls, but with additional features for manga.

Space : play/pause (anime) next page (manga)
arrowkeys : rewind/fast forward 5-30 seconds (configurable/anime) pervius/next page manga
M : mute
F : fullscreen
B : previous episode/issue
N : next episode/issue
0-9 : % of video (0=begining of video, 9=90%)
L : same as left arrow key
J : same as right arrow key

**Comment by lolamtisch** [comment]
miniMAL shortcut is implemented with 0.4.9 .
You can change the shortcuts if you want: https://github.com/lolamtisch/MALSync/wiki/Shortcuts
