### ISSUE TITLE
Missing red line indicator in chrome extension.

### ISSUE THREAD

**Issue by nishantjulian** [lolamtisch/MALSync#126]
**Describe the bug**

The Red line indicator is missing, that showed me how many episodes are left for an anime I am watching. But the same is working for the manga I'm reading.

I use it extensively to check if new episodes are up or if I have an anime that is still left to finish.

In picture: Anime Watching without the red line for 'Noragami' Anime.
<img width="513" alt="Screenshot 2019-06-29 at 4 31 05 PM" src="https://user-images.githubusercontent.com/23497194/60383347-09faac00-9a8d-11e9-8302-5fca2d38a5d1.png">

In picture: Manga reading with the red line for 'Blood Lad' Manga showing the chapters left to read.
<img width="510" alt="Screenshot 2019-06-29 at 4 38 47 PM" src="https://user-images.githubusercontent.com/23497194/60383374-475f3980-9a8d-11e9-9ccd-ae39d0d79b18.png">

**Steps to reproduce the behavior:**
1. Click in the chrome extension icon
2. Click on bookmarks icon
3. Select Anime -> Watching
4. Confirm if there is a red line for the remaining episodes

**Additional information:**
 - Browser: chrome
 - Type: extension
 - Url:

**Comment by lolamtisch** [comment]
The red line only shows up for airing animes. If they are not airing the dark blue bar is the indicator (is allways full width). So if the light blue bar is not full width and it is not an airing anime then you know there are still episodes to watch.

PS.: If there is no dark blue bar than it means there are no information to the total episode number the series had. Example black clover is open end.

**Comment by nishantjulian** [comment]
@lolamtisch, I get it now. thanks!
Although it's hard to see it in the dark theme that I'm using so I never noticed it before.
