### ISSUE TITLE
Episode count getting set to 35 when watching on Twist.moe

### ISSUE THREAD

**Issue by HyperEpsilon** [lolamtisch/MALSync#127]
I've noticed when watching shows tonight that whenever the count should update instead of getting set to the current episode the count is set to 35/n where n is the total number of episodes. It has happened on three separate animes, [Initial D First Stage](https://twist.moe/a/initial-d-first-stage/1), [Gaikotsu Shotenin Honda-san](https://twist.moe/a/gaikotsu-shotenin-honda-san/1) and [JoJo no Kimyou na Bouken Part 5: Ougon no Kaze](https://twist.moe/a/jojo-no-kimyou-na-bouken-ougon-no-kaze/1), but I haven't tested any other sites.

I believe this happened since the last update because it was tracking correctly a few days ago.

Windows 10
Chrome 75.0.3770.100

**Comment by lolamtisch** [comment]
I could not reproduce it. Are you syncing to mal, kitsu or anilist? Does it happen on every episode? I just checked the changes since the previos release and there werent no changes in the sync implementation.

**Comment by HyperEpsilon** [comment]
After restarting both my chrome and my computer the issue seems to have resolved itself, no idea what was happening. 

If it comes back I'll reopen the issue.

**Comment by HyperEpsilon** [comment]
It seems the issue has come back, I'm not sure what's causing this. [I captured a video showing what happens.](https://puu.sh/DO0wM/faebf0120f.mp4) The issue doesn't seem to happen on either kissanime or 9anime.

I just checked and it even happens with [shows I just start watching,](https://puu.sh/DO0CV/decb67192f.mp40 and I even checked my laptop which has the same issue [as seen here.](https://puu.sh/DO0Kv/f9e68ecca6.mp4)

I am happy to provide any debugging information you may need.

**Comment by lolamtisch** [comment]
@HyperEpsilon 
That is strange. It looks like the script is executed two times. Are you sure you dont have the userscipt installed too? 

Could you check the logs (F12 and then console).

I find it easier/faster to debug something like this on discord´s text chat. 
https://discordapp.com/invite/cTH4yaw

**Comment by lolamtisch** [comment]
If still a problem reopen it
