### ISSUE TITLE
Aggressive Retsuko

### ISSUE THREAD

**Issue by lipefleming** [lolamtisch/MALSync#130]
Could you fix Netflix's Aggressive Retsuko? The extension is linking with the 100ep version, rather than season 1 and 2 (ona).

Thanks in advance.

**Comment by lolamtisch** [comment]
Check the troubleshooting section on how to correct entries yourself. They get sent to my database for correction like that.
https://github.com/lolamtisch/MALSync/wiki/Troubleshooting#myanimeentry-entry-is-not-correct
