### ISSUE TITLE
Suggestion: more control over MAL tags

### ISSUE THREAD

**Issue by HyperEpsilon** [lolamtisch/MALSync#14]
Personally, I don't find the 'resume watching' tag useful, it just goes to the episode I finished watching. On the other hand, I do find the 'continue watching' tag **EXTREMELY** useful.

Having an option to turn on or off the specific tags would be super nice

**Comment by lolamtisch** [comment]
The "resume watching" tag only appears when there is no information to create the "continue watching" tag, like on the last episode of a currently airing shows. It is more like a fallback not needing to open the overview page to get the next episode. But if you want i can still add a option to hide the resume watching link, but it wont magically add the continue watching tag.

**Comment by mrabomination** [comment]
I know that it won't magically change to the "continue" tag, but I personally find the "resume" tag to be confusing and a little unnecessary. Having the ability to hide the "resume" tag would be fantastic!

**Comment by lolamtisch** [comment]
@HyperEpsilon 
Option added in version 0.2.13.
Btw the update check option can auto update the continue watching links.
