### ISSUE TITLE
Delete manga entries from local storage

### ISSUE THREAD

**Issue by hemlok89** [lolamtisch/MALSync#142]
I love the local storage feature so that I do not have to rely on any one website for bookmarks. But there is no Overview page for mangas in local storage. Clicking Overview displays [this](https://i.imgur.com/Mql9z94.png). I really don't need an page but how do I delete an entry from local storage.

**Comment by lolamtisch** [comment]
This is a bug. It is supposed to look like this. I am going to fix it with the next release.
![image](https://user-images.githubusercontent.com/12599334/61592635-19759c80-abd6-11e9-932b-504a275f7542.png)

**Comment by hemlok89** [comment]
Thank you! And if you have some spare time, please add manganelo.

**Comment by hemlok89** [comment]
The issue is solved. Closing this.
