### ISSUE TITLE
compatibility issue with kiss grabber

### ISSUE THREAD

**Issue by stapuft** [lolamtisch/MALSync#153]
![image](https://user-images.githubusercontent.com/46431157/61987522-4c100280-afe5-11e9-9758-657520cdcc20.png)
this part of the mal script disappears when using the kissgrabber user script 
https://github.com/thorio/KGrabber/
as far as I can tell there aren't any other compatibility issues, but this bar is essential when using said userscript because of how it grabs episodes.
thorio/KGrabber#19

**Comment by lolamtisch** [comment]
Fixed by thorio
