### ISSUE TITLE
Manual refresh button

### ISSUE THREAD

**Issue by hemlok89** [lolamtisch/MALSync#162]
A manual refresh button would be handy if one wants to just check for update.

**Comment by lolamtisch** [comment]
Where do you mean exactly? I added one in minimal since the last release.

**Comment by Karmesinrot** [comment]
Are you referring to the new ep/ch update check? You could go to minimal settings > update check > debugging "button".

**Comment by hemlok89** [comment]
My bad. I did not notice that debugging has this option.
