### ISSUE TITLE
MAL-Sync can not differentiate between manga & novel

### ISSUE THREAD

**Issue by hemlok89** [lolamtisch/MALSync#165]
I track some novels from novelplanet.com via Mal-Sync local storage. One of them is Tales of Demons & Gods. Also I follow the manga of this. The manga is at chapter 235 & the novel is at 480. In local storage they both have individual entries but the novel entry shows 480/235 chapters thinking it is the manga. Here is a [screenshot](https://i.imgur.com/JgK0qlX.png).

**Additional information:**
 - Browser: Chrone
 - Type: Extension
 - Url: https://novelplanet.com/Novel/Tales-of-Demons-and-Gods/c480-Reunion?id=672907

**Comment by lolamtisch** [comment]
I thought it would be extreme unlikely that something has the exact same identifier between two pages and it would make sense.
Looks like i was wrong.
Good Job 👍

**Comment by lolamtisch** [comment]
Fixed in release 0.6.1

**Comment by hemlok89** [comment]
Thank you.
