### ISSUE TITLE
Adding MAL url to a local storage entry does not recognize in index

### ISSUE THREAD

**Issue by hemlok89** [lolamtisch/MALSync#167]
Sorry for the inexplicible title & another bug report. I have a manga in local storage called Fechippurru. But I found out it has a MAL entry so I manually set the URL. When the manga page is opened, both mini-MAL & the extension shows the MAL entry. [Screenshot](https://i.imgur.com/yBhTFcI.png)

But in the main UI of the extension, the entry is still shown as a local storage entry. [PIC1](https://i.imgur.com/5xz1aGX.png) & [PIC2](https://i.imgur.com/qFUiqY3.png)

**Comment by lolamtisch** [comment]
Mal and localstorage are independent systems. You probably have the entry now 2 times in the list. Just delete the local storage one and you should be fine.

Transfering everything from local to Mal on change is not that easy. Not very high priority to fix this.

**Comment by hemlok89** [comment]
Ok. Thank you. I deleted the local storage entries.
