### ISSUE TITLE
Cannot login to myanimelist using vivaldi browser and chrome extension

### ISSUE THREAD

**Issue by TheBestPessimist** [lolamtisch/MALSync#168]
**Describe the bug**

I'm trying to authenticate using https://kitsu.io/404?mal-sync=authentication, with my username and pass (which are correct), but i always get `Credentials Wrong` when pressing the login button (btw, pressing enter to submit doesn't work either, i have to move my cursor to the login button and click it)

**Additional information:**
 - Browser: Vivaldi, based on chromium
 - Type: Extension
 - Url: https://kitsu.io/404?mal-sync=authentication

**Comment by lolamtisch** [comment]
Login still works for me.
Could you change your password to something simple and retry?

**Comment by TheBestPessimist** [comment]
The password is pretty simple, it only has 20 US letters and numbers

**Comment by lolamtisch** [comment]
Hmm
Is the email address simple enough too?
Could it be blocked by some adblocker? 

The implementation is very simple. The only thing that could fail is some wrongly encoded symbol, but it is implemented like kitsu wants it.

**Comment by TheBestPessimist** [comment]
I'm not using an email address, but the username: `TheBestPessimist`

**Comment by lolamtisch** [comment]
That could be the problem. You can check your email in the profile settings and add/change it if needed.

**Comment by TheBestPessimist** [comment]
https://i.imgur.com/6A6tcD0.png

**Comment by lolamtisch** [comment]
Is it solved? Can it be closed?

**Comment by TheBestPessimist** [comment]
Unfortunately nope, it's still not working for me

**Comment by lolamtisch** [comment]
That could mean anything really.
Had your account already an email or did you have to add it? 

Could you join the discord (bottom of the GitHub readme. We can try to fix it there or later switch to the kitsu support server together.

**Comment by lolamtisch** [comment]
Another thing. you want to use kitsu right? Because you say you want to use Myanimelist in the title but the description says kitsu.

**Comment by TheBestPessimist** [comment]
OMG i'm stupid and i misunderstood what i had to do. 

I though i had to login with my MAL credentials in that window, not with the kitsu credentials. Oh, so sorry  for wasting your time `:v(`  :-s.

**Comment by lolamtisch** [comment]
So you wanted to use kitsu? 

If you want to use MAL you need to change the `sync mode` to that in the settings.

I am closing the issue. If you still have problems just reopen it.
