### ISSUE TITLE
Timeout error in Manganelo

### ISSUE THREAD

**Issue by hemlok89** [lolamtisch/MALSync#169]
As the title suggests, checking new chapters in Manganelo is getting a timeout error. Here is a [screenshot](https://i.imgur.com/t6UHphx.png).
Here is the console output on Manganelo [screenshot](https://i.imgur.com/BKOk36a.png).

**Comment by lolamtisch** [comment]
Could be because of missing permissions. Just Set the updatecheck Interval to off and then renable.

**Comment by hemlok89** [comment]
Thank you. That solved the issue.
