### ISSUE TITLE
Import and Export

### ISSUE THREAD

**Issue by ComKhan** [lolamtisch/MALSync#171]
**Describe the bug**

When importing using miniMAL on Firefox, miniMAL will close after selecting the file instead of importing.
**Steps to reproduce the behavior:**
Have miniMAL set to default settings on Firefox. Use the Import feature. Select an exported file.
**Additional information:**
I am unsure if this is also a problem on Chrome as I have not tested it. Opening up miniMAL as a separate window fixes the problem.
 - Browser: Firefox
 - Type: Import Error

**Comment by ComKhan** [comment]
Just tested it on chrome. It's only a Firefox problem.

**Comment by lolamtisch** [comment]
Looks like that is how firefox handles it. I can not change that behavior. I am still not sure how to fix this.

**Comment by hemlok89** [comment]
I have encountered this bug. I managed to resolve this by turning on the setting "Open in seperate window"

**Comment by lolamtisch** [comment]
Added a message pointing to a seperate window.
