### ISSUE TITLE
Kitsu & Simkl auth

### ISSUE THREAD

**Issue by RootAndroid58** [lolamtisch/MALSync#175]
**Describe the bug**
whenever the minimal opens the page to sync with the above sites it authenticates but wont show up on extension (using google chrome)
cant auth or it wont auth to the extension 

**Steps to reproduce the behavior:**
go to settings->ETC -> Sync just then u will see to auth to the site and the error occurs it goes to loop 
**Additional information:**
 - Browser: chrome
 - Type:  here both tried on either too
 - Url: non or the auth url u set (anyway here it is https://kitsu.io/404?mal-sync=authentication & https://simkl.com/apps/chrome/mal-sync/connected/?code=*********************************** the code here )
![Screenshot (95)](https://user-images.githubusercontent.com/28777412/63888477-a04f3d80-c9fc-11e9-9389-eb98cdf7181b.png)
![Screenshot (97)](https://user-images.githubusercontent.com/28777412/63888651-09cf4c00-c9fd-11e9-9bd1-0482ebdbb635.png)
![Screenshot (98)](https://user-images.githubusercontent.com/28777412/63888653-09cf4c00-c9fd-11e9-9ba8-efd82049c825.png)

**Comment by lolamtisch** [comment]
You have the script running two times (double login form). Please remove the userscript version.

If you are useing the adult version just deactivate it for the authentication.

**Comment by lolamtisch** [comment]
No response. Closed for now. Please reopen if not solved
