### ISSUE TITLE
Offset helper

### ISSUE THREAD

**Issue by lolamtisch** [lolamtisch/MALSync#18]
Although while I switched from the userscript to the extension, the offsets that I fixed previously were reset.
Since the extension now loads hidden tabs to detect the last episode could it also detect the first one and set offsets accordingly? Something like an auto offset option.

_Originally posted by @Eskander in https://github.com/lolamtisch/MALSync/issues/8#issuecomment-435091748_

**Comment by lolamtisch** [comment]
@Eskander
I would say it is a bit too risky like that. 
But adding a popup recommending a possible offset when opening a overview streaming page should do the job.

**Comment by Eskander** [comment]
Why would that be risky? If anything goes wrong the user will have to set the value manually and the extension should ignore updating manually set offsets. Maybe a switch to set a manual offset would be needed in that case.
Besides, the new Update Check feature is giving some wrong values because of the unset offsets.

**Comment by lolamtisch** [comment]
There is so much that can go wrong, because many pages use pagination, ajax pagination etc..
I dont trust my implementation enought, for such a critical value.
Especially for a new user a wrong offset is a lot more confusing than a missing offset. For me a user confirmation is a must here.

UpdateCheck:
You can check the state in the debugging page of the updateCheck settings. Finished entrys are not checked again. So the entrys with a wrong offset are probably marked as finished and will stay like that. 

Current Workaround:
There is no other way atm than using the "delete cache" button in miniMAL to reset the update check entries. This unfortunately deletes the offset values too. So you will have to set them all again and then restart the updateCheck. 
This workaround is more then suboptimal i would say. Will be better with the next update.

TODOs:
- Add buttons to the debugging page to reset individual entries
- Reset updateCheck entry on offset change.
- Move offset variables into the permanent sync storage

**Comment by Eskander** [comment]
>  Finished entrys are not checked again. So the entrys with a wrong offset are probably marked as finished and will stay like that.

That's exactly what was happening. Following the Current Workaround fixes the issue. Thanks.
