### ISSUE TITLE
Updates corrupt certain characters in entry comments

### ISSUE THREAD

**Issue by NotJim99** [lolamtisch/MALSync#180]
Making any sort of updates to MAL entries (chapters/volumes read, episodes watched, score, status) using the extension will corrupt certain characters like apostrophes, quotation marks, and colons in said entry's comments and change them into either their HTML character codes when done from the MiniMAL window or a string of garbage followed by the character code when done using other means like the popup at the bottom of the page or the embed on the series' page on reader sites.

So an entry comment like:

`This's an example.`

Would become:

`This&amp;amp;amp;amp;amp;amp;amp;amp;#039;s an example.`

When the entry is edited through most means, and:

`This&#039;s an example.`

When the entry is edited with MiniMAL.

By entry comments, I mean this part here, in case that wasn't clear.

![Comments](https://user-images.githubusercontent.com/16053022/64061573-6c158180-cba2-11e9-9b46-317cf4f746d2.png)

**Comment by lolamtisch** [comment]
It is probably only missing encoding on the comments section before sending it to MAL. Will soon look into it.

**Comment by NotJim99** [comment]
Yeah, that seems to have fixed it. Thanks.
