### ISSUE TITLE
Animeflix.io does not work

### ISSUE THREAD

**Issue by Chup123** [lolamtisch/MALSync#185]
**Describe the bug**
In the last update animeflix was added to the list op supported sites. But it doesn't work for me. When I play RE:ZERO it doesn't scrape the video. 

**Steps to reproduce the behavior:**
Look for RE:ZERO on animeflix and look if it works. I watch the dub for reference

**Additional information:**
 - Browser: Brave (Based on chromium)
 - Type: Extension
 - Url: http://animeflix.io/shows/rezero-kara-hajimeru-isekai-seikatsu/episode-9-458309/dub

**Comment by lolamtisch** [comment]
Known bug. Reload on the video page should be temporary workaround.

**Comment by henrik9999** [comment]
Should work now with the new release
