### ISSUE TITLE
9anime.to gets redirected to 9anime.nl

### ISSUE THREAD

**Issue by Not-James-Bond** [lolamtisch/MALSync#195]
**Describe the bug**
When we open any 9anime site(through MAL) for the last season animes(most of them) which has url of 9anime.to/* redirects to new 9anime.nl(Home Page). Wherease it works for old and new season anime with 9anime.ru/* links.

**Steps to reproduce the behavior:**
Open This Link https://myanimelist.net/anime/38573/Tsuujou_Kougeki_ga_Zentai_Kougeki_de_Ni-kai_Kougeki_no_Okaasan_wa_Suki_Desu_ka/
Click on 9anime link.

**Additional information:**
 - Browser: FireFox Quantum
 - Type: Extension
 - Url: https://myanimelist.net/anime/38573/Tsuujou_Kougeki_ga_Zentai_Kougeki_de_Ni-kai_Kougeki_no_Okaasan_wa_Suki_Desu_ka

**Comment by lolamtisch** [comment]
All links are currently .ru . I changed it last week. They are cached in the extension. Just clear the cache in the settings of mal-sync. 

Everything else has to be fixed by 9anime.

**Comment by Not-James-Bond** [comment]
Ahh thanks. It was from my side then.
