### ISSUE TITLE
Fails to display UI Design

### ISSUE THREAD

**Issue by FunkyJustin** [lolamtisch/MALSync#2]
I have submitted the following review in the firefox addon page:

I am currently using the Firefox Nightly browser and
I'm experiencing a problem in regards to the UI
as provided in the link:
http://prntscr.com/l43joq

The UI is not shown as it was portrayed in the screenshot and an element is clipping through the text.

A similar problem is happening to when I browse over the episode selection and information portion of the anime and pressing the menu button as seen here:
http://prntscr.com/l43pko

From both of these, I can see a problem with the UI design failing to be displayed as seen in the screenshots.

**Comment by lolamtisch** [comment]
@FunkyJustin 
It looks like this only happens on the unstable version of Firefox (beta/nightly). I am going to investigate if I can somehow fix it.

**Comment by lolamtisch** [comment]
@FunkyJustin 
Version 0.2.7 should fix this
