### ISSUE TITLE
Prediction not showing up in modern Style

### ISSUE THREAD

**Issue by Whitedoteu** [lolamtisch/MALSync#20]
**Describe the bug**
In the modern List Design, the "predictionPos"(aired episodes") are not showing up. 
In the Detail View, it works fine. 
[Img Modern List](https://i.imgur.com/TRz6UTX.png)
[Img Detail View](https://i.imgur.com/in0Wgj8.png)

**Steps to reproduce the behavior:**
set the Anime List to modern and look at the episodes. 

**Additional information:**
 - Browser: chrome
 - Type: Userscript Tampermonkey
 - Url: https://myanimelist.net/animelist/Beastyrabbit?status=6

**Comment by lolamtisch** [comment]
This happens when there is no relation to a streaming page (url in tags). Will be fixed in the next release.

**Comment by lolamtisch** [comment]
@Whitedoteu 
Should be fixed in version 0.2.13
