### ISSUE TITLE
Related anime in separate lines 

### ISSUE THREAD

**Issue by AccelerateIzaya** [lolamtisch/MALSync#21]
Hi,
I wanted to request a small thing. 

Is there any way to put the related anime in separate lines?

For example;

From this
![](https://cdn.discordapp.com/attachments/358599430502481921/509767999184568330/unknown.png)

to this
![](https://i.imgur.com/eRa56k4.png)

Ah, it would be better if there were no "comma" in any of the places and the names would be in separate lines, not just of the Side Story.

**Comment by H4Z3** [comment]
i did a thing! Here, take this [Line Breaker for MyAnimeList](https://greasyfork.org/en/scripts/374086-line-breaker-for-myanimelist)

**Comment by lolamtisch** [comment]
@AccelerateIzaya Is that enought for you? If yes just close the issue.

**Comment by AccelerateIzaya** [comment]
@lolamtisch Ah yes. That's enough for me. :)

**Comment by AccelerateIzaya** [comment]
>close
