### ISSUE TITLE
website add animelab aus 

### ISSUE THREAD

**Issue by trenton4k** [lolamtisch/MALSync#211]
can you add https://www.animelab.com 
example of series 
https://www.animelab.com/shows/my-hero-academia
https://www.animelab.com/shows/magical-girl-spec-ops-asuka
sample of episode
https://www.animelab.com/player/my-hero-academia-episode-67
https://www.animelab.com/player/magical-girl-spec-ops-asuka-episode-2

**Comment by henrik9999** [comment]
for now not possible because of the page layout/design
