### ISSUE TITLE
MAL preventing syncing

### ISSUE THREAD

**Issue by TimeHopper** [lolamtisch/MALSync#216]
When trying to sync, if a score on kitsu/anilist isn't an integer, the extension will hang when trying to sync it to mal and will not update other databases

**Comment by lolamtisch** [comment]
Working on it will take some time

**Comment by TimeHopper** [comment]
> Working on it will take some time

ok

**Comment by TimeHopper** [comment]
It seems this also applies to missing anime/manga

**Comment by TimeHopper** [comment]
ack didnt mean to close it

**Comment by Argzero** [comment]
Seconding. Mine fails on an anime of chinese origin which has its Japanese name on anilist.co, but its chinese name on MAL.

**Comment by lolamtisch** [comment]
@Argzero 
The Problem are wrong mal ids on anilist, so less a problem of mine. It points to the anime with the id 39402 which does not exist on mal. On the left side on anilist you can edit them with the edit button. I already submitted a correction, now anilist has to review it.

![image](https://user-images.githubusercontent.com/12599334/74016958-99592d80-4993-11ea-9252-fda45e62dbe2.png)


All the pages sync implementations where never intended for this usage and have very bad error handling. That is kind of the problem, i cant really detect if an update fails. This needs a rewrite which takes time.

**Comment by henrik9999** [comment]
This should be fixed closing this for now
