### ISSUE TITLE
Chrome version is outdated

### ISSUE THREAD

**Issue by TimeHopper** [lolamtisch/MALSync#217]
This isn't really a bug, but the chrome version of the extension is still on 0.6.5 not 0.6.6

**Comment by lolamtisch** [comment]
Pending review by Google. Takes a lot longer than normal.

**Comment by TimeHopper** [comment]
> Pending review by Google. Takes a lot longer than normal.

Ah k sorry bout that

**Comment by lolamtisch** [comment]
No problem. You are not the first one asking. XD
