### ISSUE TITLE
All watched episodes are marked blue

### ISSUE THREAD

**Issue by jb-99** [lolamtisch/MALSync#221]
Currently all watched episodes are being marked blue as if they were last watched, instead of only the last episode being marked.

It just started happening after the latest update I think.

 The browser is Google Chrome. The site is kissanime.ru

**Comment by henrik9999** [comment]
this is expected behavior im working on a setting to disable this though

**Comment by jb-99** [comment]
So it's like this by default? [Screenshot](https://imgur.com/Bwa1Rdl)? Why was this changed from most recently watched to all watched ones?

**Comment by henrik9999** [comment]
yeah its like that by default i thought it would look better

**Comment by jb-99** [comment]
Oh ok, I thought it was a bug >,<
