### ISSUE TITLE
Wrong episode being marked as 'watched'

### ISSUE THREAD

**Issue by jb-99** [lolamtisch/MALSync#223]
When looking at a list of episode on kissanime, the episodes that I've watched are not being marked, instead the episodes that were not watched are being marked. The example - [SCREENSHOT](https://imgur.com/vb2h8Ms). The episodes that are being marked are the uncensored versions and are marked with an _ on kissanime. The issues just started happening after the latest update.

The issue happens on it's own.

Browser: Google Chrome

**Comment by lolamtisch** [comment]
It was like that already before the update.
With the next update it will mark both as watched. 
Mal-sync does not keep track if you watch the normal or uncensored version. Currently it just marks what is last in the list.

**Comment by jb-99** [comment]
It's weird, because just a few days ago it was showing correctly...
