### ISSUE TITLE
Episode offset detection is wrong

### ISSUE THREAD

**Issue by jb-99** [lolamtisch/MALSync#229]
The  episode offset detection system is definitely bugged. I just started watching JoJo's Bizzare Adventure Stardust Crusaders Season 2 on kissanime.ru and I got a promt saying something along the lines "Offset of -1 episode detected...". I accepted it and as soon as I watched ep 1 (marked as ep 25 on kissanime) it set it as completed on MAL. It always worked flawlessly, but I presume the last update a few days ago bugged it. Well I don't know if it was the update, but I had to again accept the permissions prompt or on MAL-Sync, otherwise it wouldn't run.

Browser: Google Chrome

**Comment by lolamtisch** [comment]
It has nothing to do with the last update. It probably always failed on that anime. It is the Opening 002 that gets detected as episode breaking everything. We even already wrote a fix for that last week. 

You will have to manually change the offset. https://github.com/lolamtisch/MALSync/wiki/Troubleshooting

**Comment by lolamtisch** [comment]
Should be fixed with the new update
