### ISSUE TITLE
Add KissAnime Bookmarks Export

### ISSUE THREAD

**Issue by redditreaper86** [lolamtisch/MALSync#23]
Please could you add a button or something to sync all current kissanime bookmarks or maybe export to xml. the current userscript doesnt work

**Comment by lolamtisch** [comment]
With my script you only can add them one by one and adding an export it is to much work atm.
But I can recommend you this userscipt. It does exactly the thing you want. I just tested it and it is still working.
https://greasyfork.org/en/scripts/19939-kissanime-bookmarks-to-myanimelist-export-2018

**Comment by redditreaper86** [comment]
It's working for you? Just sticks for me after hitting 69 and i have like
300 i need backed up :-\ damn ok

**Comment by lolamtisch** [comment]
@redditreaper86 
I did a backup of 329 entries without a problem.
You could check in the console where it gets stuck and remove that entry from the list.
(Press F12 on the keyboard and then in the console tab)
