### ISSUE TITLE
"instant" episode detection, isn't so instant/possiblie compatibility issue

### ISSUE THREAD

**Issue by stapuft** [lolamtisch/MALSync#235]
**Describe the bug**
I use this userscript in order to grab multiple episode links at the same time
https://github.com/thorio/KGrabber
how it works is it keeps a "list" of the episodes you want in memory, and goes to those pages one by one, grabs the direct video link from the HTML5 video player as it loads, and then moves on to the next episode.
weather I use this to grab one episode or many, it never seems to go "slow" enough fo mal sync to register that I am watching the episodes, even though to goes to each individual page to grab the episode links.
**Steps to reproduce the behavior:**
install this userscript https://github.com/thorio/KGrabber
![image](https://user-images.githubusercontent.com/46431157/68334521-c94d1800-00a8-11ea-8959-f7f5c87a4338.png)
either click "grab" by the episode number in the episode list, or type in the range of episodes in the new container on the right and pick your server, then click grab
do the capcha
wait
it will load back to the main page with a direct link to the video, but mal-sync remains un-updated.
![image](https://user-images.githubusercontent.com/46431157/68334622-01ecf180-00a9-11ea-8876-98226b96b7f5.png)

**Additional information:**
 - Browser: Firefox 70.0.1 (64-bit)
 - Type: extension
 - Url: kissanime, site wide.

**Comment by lolamtisch** [comment]
I tested and it works. The entry has to be set to watching as if not it always ask to start watching.

It probably can miss episodes if mal/anilist etc or you internet connection are too slow. But that are things I can not fix. 
Only solution is to modify the KGrabber and increase the timeout on the page.

**Comment by stapuft** [comment]
then thats what ill look into doing, my internet speed is rather ripping fast, I have no control over mal/anilist/kitsu though.
I should have picked a better example page, because it does the same thing on shows I have set as watching.

**Comment by thorio** [comment]
Is there a way for me to just tell MALsync explicitly? If there is an exposed function or something similar, I can easily add this.

**Comment by lolamtisch** [comment]
There aren't any exposed functions. Webpack is completely closed down by default. 

I think a simple timeout should be enough here, as it is a very dumb use of malsync.

**Comment by thorio** [comment]
You can still interact with window or listen for events.
I agree on the last part though. Since MALsync is compatible with Plex and Emby, OP might as well use either one. Then it will also track what you've actually watched, not just downloaded.

**Comment by stapuft** [comment]
> 
> 
> You can still interact with window or listen for events.
> I agree on the last part though. Since MALsync is compatible with Plex and Emby, OP might as well use either one. Then it will also track what you've actually watched, not just downloaded.

well I do have access to plex, but its not my plex server, so I can't really install or add anything to it, and my buddy only has subbed anime, movies, and live action stuff on his plex, so I tend to use it for more live action stuff and movies.

I am basically using malsync as a "universal" watchlist, for my anime
I have access to a fire TV stick (first Gen, with an old version of kodi on it that I haven't used since S.A.L.T.S. died, and they removed the actual YouTube app from)
a roku TV (tcl multiple years old)
and a shitty computer,with almost no harddrive space, hooked up to that 720p roku TV, that I end up doing most things from (said computer sucks so much that watching videos in the HTML5 player can have some hang-ups and freezes so I use VLC to stream my entertainment, instead of downloading things.


in my extremely nieche situation your combo of userscripts makes my life amazing and I have no idea what hoops I would have to jump through to do things the "normal" way, but if you have any suggestions of what I could do, like using emby, which I've never tried before, I'm all ears.

**Comment by thorio** [comment]
I would suggest setting up your own Plex server on your pc. Since you have almost no harddrive space that might be an issue though.

**Comment by lolamtisch** [comment]
You can change the episode/state by hand on the kissanime page and it will add the link to that page.
I have a ultra week pc (dualcore 1.83 ghz, 2gb ram, 32gb hd) that I use for watching videos. With firefox i never had problems with freezes and the display is slightly over fullHD. Only problem i have is that it overheats sometimes and then it goes down to 0.5 ghz, but that is to be expected.

**Comment by stapuft** [comment]
I honestly think that overheating is my biggest issue, my computer is one of those ultra thin netbook laptops, I've done about everything I can to keep it running cool, but all the components are crammed in there so tightly, plus I live in one of the hottest states, and my office, is nicknamed "the sun room" because of how how it gets, but I got it right in the breeze zone of a wall unit a/c that runs 24/7, and I got a fan blowin air on it while I use it too, still especially around 1-3 PM it likes to freeze and hang up, alot, especially if I'm trying to watch a HD movie or use Gimp.

I just need to bite the bullet and build a new computer, its been too long anyway, I ain't had a desktop since I left for university.

**Comment by lolamtisch** [comment]
I think this is resolved
