### ISSUE TITLE
Extension disappearing

### ISSUE THREAD

**Issue by PointBlank776** [lolamtisch/MALSync#250]
**Describe the bug**

Extension seems to uninstall itself. I'd then go to reinstall but chrome store then claims it's still installed despite it being inaccessible.
**Steps to reproduce the behavior:**
Usually happens after I restart my pc
**Additional information:**
 - Browser:  Chrome
 - Type:  Extension
 - Url: Is a URL to something really needed for an issue that revolves around the extension itself?

**Comment by lolamtisch** [comment]
1) Does it show up in chrome://extensions/ ?
2) If yes it is enabled or disabled?
3) If it is disabled, do you have an extension that disables extension to save ram (like NooBoss)

No idea what it could be else.

**Comment by RootAndroid58** [comment]
that may be because of a malware try scanning ur pc with good antivirus (malwarebytes or ur choice ) also re install google chrome hope it will work

**Comment by lolamtisch** [comment]
Closing for now
