### ISSUE TITLE
gogoanime.io episodes updates fails every time

### ISSUE THREAD

**Issue by RootAndroid58** [lolamtisch/MALSync#251]
**Describe the bug**
as u know the mal sync updates anime ep as soon as u start watching it working in kissanime.ru , kickassanime.io but it fails every time in gogoanime.io 
also the userscript stucks in gogoanime.io in white screen every single time 

**Steps to reproduce the behavior:**
watch any anime in gogoanime.io

**Additional information:**
 - Browser: chrome
- Type: Extension/Userscript (both)
 - Url: https://www10.gogoanime.io/black-clover-tv-episode-110

**Comment by lolamtisch** [comment]
What do you use as provider (mal/kitsu/anilist/simkl)?
What do you mean with stuck in white screen?
Does it fail for all animes or just for black-clover?
It works for me with gogoanime.


![image](https://user-images.githubusercontent.com/12599334/69235610-17c2e200-0b92-11ea-9378-7960a3af2ae0.png)

**Comment by RootAndroid58** [comment]
idk the mal tampermonkey script doesnt load ie it shows the white box but not loading and every time it shows update failed shall i try to reinstall script and mal sync ?
tell me a method to debug so that i can send u the log 
provider mal and it stuck on all anime 
see the screen shot
![Screenshot (128)](https://user-images.githubusercontent.com/28777412/69396521-82962980-0d08-11ea-9bdb-d61831f61826.png)

**Comment by RootAndroid58** [comment]
if u click the floating button for mal it gets stuck only in gogoanime.io every other site is fine

**Comment by lolamtisch** [comment]
Running both the extension and userscript at the same time can result in errors. But i dont think that is the problem here.

I suspect that you have an aggressive adblocker / cookie blocker / privacy setting , which blocks the requests by malsync. It is new to me that extension request get blocked on page basis, but i think it is theoretically possible.

For debugging. You could check the console on gogoanime most things of malsync are logged there.

**Comment by RootAndroid58** [comment]
yah after i reinstalled the extension its finally finallyyyyyyyyyyy workinggggggggggg XDDDDDD

**Comment by plW0lf** [comment]
Reopening as the error just returned - it doesn't automatically updates anime with video option enabled. (manual stil works). Already reinstalled userscript and used both with adblock on (which previously worked) and off.
**additional info**
- browser: chrome
- type: userscript
- url: https://www12.gogoanime.io/grisaia-no-kajitsu-episode-4
