### ISSUE TITLE
streaming list shortcut in MAL browse page

### ISSUE THREAD

**Issue by andrizmitnick** [lolamtisch/MALSync#260]
is possible to add this feature? adding streaming list shortcut when in MAL browse page, like this one for example. btw thanks before
![chrome_2019-12-05_04-21-11](https://user-images.githubusercontent.com/21377475/70183347-2f64a380-1718-11ea-9649-6715de86bb17.png)

**Comment by lolamtisch** [comment]
Unfortunately it would mean a lot of API calls (4 - 20+ per anime). That would burn through my API usage plan very fast. Performance whise it would be very slow and it is not that useful in the end.
😅

**Comment by andrizmitnick** [comment]
Ah right, just realized that it wouldn't make much difference most of the time and between the majority of user. right, i think it's better as it is now. Thanks for the explanation
