### ISSUE TITLE
Kitsu Side sources Un-scrollable 

### ISSUE THREAD

**Issue by as280093** [lolamtisch/MALSync#261]
**Describe the bug**
In Kitsu, When an anime page is opened the side panel shows all the streaming sites including kissanime and others. but it cant be scrolled 

**Steps to reproduce the behavior:**

1. Open any anime page on Kitsu 
2. See side panel, or click search 

**Additional information:**
 - Browser: chrome
 - Type:  Userscript
 - Url: https://kitsu.io/anime/kawaikereba-hentai-demo-suki-ni-natte-kuremasu-ka

**Comment by lolamtisch** [comment]
I dont understand. It scrolls just fine when you go down. The only page where you have to scroll a bit more is the reactions page, but the overview page is fine. 
![image](https://user-images.githubusercontent.com/12599334/70330799-8ebcd380-183e-11ea-9523-656d7baf1b83.png)

**Comment by as280093** [comment]
yaa what if the page has alot of reactions
why not have a separate hover on scroll for links

**Comment by lolamtisch** [comment]
I can't follow. What are reactions? I have never seen any problems on kitsu. I could move the links to the right sidebar, as the scrolling is different implemented there.

**Comment by as280093** [comment]
Dr Stone has alot of post(reactions and its hard to scroll, you need to go to bottom just to view to whole box
![GIF](https://user-images.githubusercontent.com/25240839/70388360-91eac780-19d6-11ea-860c-d644441a226e.gif)

**Comment by lolamtisch** [comment]
That is strange. I have never seen that. Alright I am going to move it to the other sidebar.
![download](https://user-images.githubusercontent.com/12599334/70392314-20634700-19df-11ea-8289-ab936ec5d64d.gif)

**Comment by lolamtisch** [comment]
Added in version 0.6.9.
