### ISSUE TITLE
[Feature Request] Add Watch anime to Bookmark(Kissanime)

### ISSUE THREAD

**Issue by as280093** [lolamtisch/MALSync#262]
Kissanime has a bookmark feature and i cant add every anime to bookmark and mark as watched,
is it possible to  bookmark it and mark as watched when no more unwatched episodes are present

**Comment by lolamtisch** [comment]
I am not sure what you exactly mean. But we decided to not add any features that use streaming site bookmark systems.
One of ideas behind malsync is that you don't need them anymore. 
They are often not very good performance whise too.

**Comment by as280093** [comment]
kissanime provides email notification whenever new episode but only when the last episode is marked as watch, i could prefer if MALSync notifies me whenever my tracked episode has new episode on kissanime

**Comment by lolamtisch** [comment]
There is a feature for that. "Update check" can check for new episodes in the background and will sent out a notification. Just enable it in the settings. Furthermore you can always see in the anime list if there is a new episode. If there is a red(update check) then there is a new ep. if there is a yellow bar (jp prediction) then there is a new episode or atleaset soon.
![image](https://user-images.githubusercontent.com/12599334/70388429-e9c30780-19b1-11ea-872a-d48e514b95ab.png)
