### ISSUE TITLE
Pretty sure you have a typo in your code (Polish only)

### ISSUE THREAD

**Issue by Aonodensetsu** [lolamtisch/MALSync#264]
**Describe the bug**
Shows "Variable $videoDuretion$ used but not defined." error.
**Steps to reproduce the behavior:**
Try to install using chrome store.
**Additional information:**
 - Browser: Chrome
 - Type: Extension
 - Url: https://chrome.google.com/webstore/detail/mal-sync/kekjfbackdeiabghhcdklcdoekaanoel?utm_source=chrome-ntp-icon

**Comment by lolamtisch** [comment]
Temporary workaround. Switch browser to other language than polish

**Comment by lolamtisch** [comment]
Fixed in version 0.6.9.
