### ISSUE TITLE
support sorting anime/manga list in miniMAL

### ISSUE THREAD

**Issue by fuzetsu** [lolamtisch/MALSync#270]
Current sort method seems to be alphabetical putting localstorage entries first. 

It would be nice if we could sort by most recently read/updated as well. I have quite a few anime/manga in my actively reading list and it would be nice to have the most recently read ones on top since some of them I have semi on hold. 

Wouldn't be as bad if I was better at grooming my reading/watching list, but alas I am not. I think it would be a nice addition. 

P.S. excellent extension :100:

**Comment by lolamtisch** [comment]
I would love to add that Feature, but unfortunately Mal has no possibility to sort by recent updated. We can just hope that they add that sorting possibility to the new api in the beginning of next year.

**Comment by fuzetsu** [comment]
Ah, I see :frowning: 

I haven't dug into the code yet, but I was kind of imagining it as a client side sort based off local information, but based on your reply I'm guessing MALsync doesn't track what/when was updated?

**Comment by lolamtisch** [comment]
Looks like there is a hidden way to sort by last updated in MAL. But Localstorage entries will still always be put in front as there is no last update date to sort it on.

https://myanimelist.net/animelist/lolamtisch?status=7&order=5

**Comment by fuzetsu** [comment]
Oh nice! That's seems pretty good to me :thinking: 

It's fairly rare that MAL et al. doesn't have the entry unless you're readying obscure (usually non-Japanese) web comics, so not that many LS entries anyway.

**Comment by lolamtisch** [comment]
I think it makes most sense to only sort by last update in watching.
Will be part of the next release later this week.

**Comment by fuzetsu** [comment]
Awesome! That makes sense to me, no need for additional UI to change the sort (I assume that's the implication?)

**Comment by lolamtisch** [comment]
Exactly. No separate UI. But someday when I have less things on my to-do list I will add sorting options to the list.

**Comment by lolamtisch** [comment]
Added in version 0.6.9.
