### ISSUE TITLE
Wakanim auto fullscreen

### ISSUE THREAD

**Issue by Arias800** [lolamtisch/MALSync#271]
**Describe the bug**
On Wakanim there is a bug when the automatic full screen is activated. Because when the video automatically switches to full screen, then the player interface doesn't appear.

**Steps to reproduce the behavior:**
For reproduce you need to start watching any video on Wakanim with the auto fullscreen option set on enable

**Additional information:**
 - Browser: Firefox
 - Type: Extension

**Comment by lolamtisch** [comment]
Will be fixed in the next update

**Comment by Arias800** [comment]
Thank's, that's works so I close the issue ^^
