### ISSUE TITLE
Not working on AnimeUltima and AniWatch

### ISSUE THREAD

**Issue by rentela** [lolamtisch/MALSync#273]
**Describe the bug**
The extension currently is not working on animeultima and aniwatch. The icon tat should appear on the page is not appearing.

**Steps to reproduce the behavior:**

**Additional information:**
 - Browser: chrome
 - Type: Extension
 - Url: https://www16.animeultima.eu/

**Comment by henrik9999** [comment]
Aniwatch does not work on chrome because the latest Mal sync update is still under review there

**Comment by lolamtisch** [comment]
Animeultima works for me too. 
Aniwatch will work when google accepts the update. We are already waiting since last Friday.

**Comment by rentela** [comment]
Thx. I will check again Animeultima.
