### ISSUE TITLE
MangaNelo redesign breaks update check

### ISSUE THREAD

**Issue by hemlok89** [lolamtisch/MALSync#274]
Yesterday MangaNelo rolled out a redesign of their site. This broke the update check for the extension.

[Screenshot](https://i.imgur.com/QU9yrsz.png)

**Additional information:**
 - Browser: Chrome Latest Stable
 - Type: Extension
 - Url:

**Comment by lolamtisch** [comment]
Yeah some features broke. It is still usable but not very good. It will take some weeks until we can publish a fix.

**Comment by lolamtisch** [comment]
Fixed in release 0.6.10
