### ISSUE TITLE
9anime new domains

### ISSUE THREAD

**Issue by distren** [lolamtisch/MALSync#276]
There are 4 new 9anime domains, listed [here](https://www.reddit.com/r/9anime/comments/e7q6jx/there_are_new_mirrors_to_access_real_9anime/), and they don't seem to be in this extension yet.

**Comment by lolamtisch** [comment]
Added. Will work with the next release in a few weeks. Just use the working mirrors for now.
to, is, ru, ch, nl, live, one

**Comment by antocs** [comment]
> Added. Will work with the next release in a few weeks. Just use the working mirrors for now.
> to, is, ru, ch, nl, live, one

They added .movie today, if I try to go back to one of the old, it changes back to .movie so, atm, I can't use MAL-Sync.
https://gyazo.com/a04595a0043703bcbf47537722cc4e1f

**Comment by distren** [comment]
Fine with me.
