### ISSUE TITLE
Branitube new version, MALSync broken

### ISSUE THREAD

**Issue by maz1no** [lolamtisch/MALSync#278]
**Describe the bug**
The website has changed into a new version, so the MALSync is now broken. We would be thankful if you guys fix the issue.

**Steps to reproduce the behavior:**

**Additional information:**
 - Browser: both
 - Type: Userscript
 - Url: https://www.branitube.net/

**Comment by lolamtisch** [comment]
known problem. 
Will take a few weeks to fix.

**Comment by henrik9999** [comment]
Known problem already fixed will be in the next release

**Comment by maz1no** [comment]
Cool, guys. Thanks a lot!

**Comment by lolamtisch** [comment]
Fixed in release 0.6.10
