### ISSUE TITLE
Gogoanime new domain

### ISSUE THREAD

**Issue by antocs** [lolamtisch/MALSync#279]
Today I open gogoanime and there is the announcement of the new domain (.movie), I can't use the one I used before cause now it change automatically to .movie, so atm I can't use MAL-Sync on gogo.

**Comment by RootAndroid58** [comment]
yah gogoanime.io moved from gogoanime.io to gogoanime.movie

**Comment by plW0lf** [comment]
Small workaround for userscript: using option to edit script, use find and replace option from gogoanime.io to gogoanime.movie
You can also instead of .movie add .*

It's just workaround before update comes :)

**Comment by antocs** [comment]
I saw the fix above got committed, when will the extension be updated?

**Comment by lolamtisch** [comment]
Probably next week + the time google needs to review the release (1-2 weeks).

**Comment by antocs** [comment]
It seems they changed it again.
Today i turn on my PC and the domain is back to .io, and the extension works again without the update.

**Comment by RootAndroid58** [comment]
> Probably next week + the time google needs to review the release (1-2 weeks).

hmm then atleast update the tampermonkey script so that it will work there

**Comment by lolamtisch** [comment]
Fixed in release 0.6.10
