### ISSUE TITLE
Firefox Multi-Account Containers

### ISSUE THREAD

**Issue by flcmc** [lolamtisch/MALSync#28]
Do you think you could add support for the [Firefox Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) extension?

**Comment by lolamtisch** [comment]
Enable strict cookies in the miniMAL popup and then restart firefox.
![image](https://user-images.githubusercontent.com/12599334/50575298-e5cf5280-0dfc-11e9-8dd6-81c8faa8d0ea.png)

**Comment by quietlystorming** [comment]
Hmm... is container support possible in the userscript? I don't see any strict cookies option there.

**Comment by lolamtisch** [comment]
@quietlystorming
Nope there is no container support in the Userscript. There is no way that I could add it, you would have to ask the Userscript manager (tampermonkey/violent monkey) to add it.

**Comment by quietlystorming** [comment]
Hmm. Guess it's time to use the add-on then. Thanks.
