### ISSUE TITLE
Shigahime not loading in extension

### ISSUE THREAD

**Issue by rentela** [lolamtisch/MALSync#281]
**Describe the bug**
The Manga Shigahime does not appear in the list of reading mangas and looking for the manga the extension keeps loading and does not retrive data

**Steps to reproduce the behavior:**
Try to search the Shigahime through the extension or try to add the manga to the reading list. In my case does not appear in the extension.

**Additional information:**
 - Browser: chrome
 - Type: Extension
 - Url: https://myanimelist.net/manga/110922/Shigahime

**Comment by rentela** [comment]
I was reading from MangaNelo but now that i am reading from MangaKisa, i don´t have any problems and the manga appears in the extension list. Don´t know if the problem was related with MangaNelo or if was another issue.

**Comment by henrik9999** [comment]
MangNelo is currently broken it will be fixed next release

**Comment by rentela** [comment]
Thx
