### ISSUE TITLE
MALSync not opening on Firefox on Wayland with Hardware Acceleration enabled

### ISSUE THREAD

**Issue by sheepymeh** [lolamtisch/MALSync#286]
**Describe the bug**
A white popup flashes in place of MALSync when it is opened. Sometimes it closes and reopens after a moment.

**Steps to reproduce the behavior:**
1. Run Firefox in Wayland using `MOZ_ENABLE_WAYLAND=1` environment variable _(Unsure whether issue exists on Xorg or other operating systems)_
2. Set `layers.acceleration.force-enabled` to true in `about:config`

**Additional information:**
 - Browser: Firefox 72 on Linux **(problem does not exist on FF71)**
 - Type: Extension
 - URL: All websites

**Log from about:debugging**
![image](https://user-images.githubusercontent.com/26665333/72253827-64301880-363d-11ea-8ccc-eaf41429c3aa.png)

**Comment by lolamtisch** [comment]
I am not sure how to help you with this. Sounds more like a firefox or Wayland problem.

**Comment by Eskander** [comment]
Pretty sure this has been fixed in recent releases of Firefox. I used to have the white popup bug on Wayland with other extensions as well.
The popup now is displayed as expected on Firefox 74 on Wayland, with/out Hardware Acceleration.

**Comment by lolamtisch** [comment]
I will close it for now then
