### ISSUE TITLE
[Firefox] Preferences box expands

### ISSUE THREAD

**Issue by SheepKid12** [lolamtisch/MALSync#291]
I don't know how else to describe the issue in text, so I recorded a short video of this happening (which I converted to a GIF, because GitHub wouldn't take the mp4):

Note: I am using the latest beta of Firefox (73.0b7), but I was also seeing this on the latest stable version.

![mal-sync-ffx-bug](https://user-images.githubusercontent.com/60110745/72824370-c0e19380-3c3a-11ea-851c-415f53579cd3.gif)

**Comment by lolamtisch** [comment]
known Problem.
But I have no idea why that happens and how to stop it. It is some strange firefox bug. 
I did ignore it, As it not specialy problematic for the usage of the settings page and 99% of the people use the settings page in the extension popup.

**Comment by lolamtisch** [comment]
Firefox fixed the bug in version 74.0
