### ISSUE TITLE
Add Prime Video

### ISSUE THREAD

**Issue by VSuhas22** [lolamtisch/MALSync#293]
Some anime are exclusive to Prime Video, like the recent Vinland Saga,
can you add Prime Video integration too, or would that be too hard?

**Comment by henrik9999** [comment]
We need an account for this probably

**Comment by VSuhas22** [comment]
@henrik9999 what account?
Also, why is this labeled as blocked?

**Comment by henrik9999** [comment]
> @henrik9999 what account?
> Also, why is this labeled as blocked?

An Amazon prime account we don't have one

**Comment by VSuhas22** [comment]
> > @henrik9999 what account?
> > Also, why is this labeled as blocked?
> 
> An Amazon prime account we don't have one

Oh okay, that makes sense.

**Comment by JiLleON** [comment]
I can give you an account with a subscription if you still need one

**Comment by JiLleON** [comment]
I can give you an account with a subscription if you still need one

**Comment by henrik9999** [comment]
> I can give you an account with a subscription if you still need one

Come and join the discord server and talk to one of us devs please https://discordapp.com/invite/cTH4yaw

**Comment by lolamtisch** [comment]
Support added. Only works on https://www.primevideo.com/

**Comment by Hayatory** [comment]
Is there possibility to add Amazon video? because in the US primevideo pretty much forces you and redirects to use the main amazon website to watch anything whereas outside the US primevideo is the main player website it seems.

**Comment by Hayatory** [comment]
> Is there possibility to add Amazon video? because in the US primevideo pretty much forces you and redirects to use the main amazon website to watch anything whereas outside the US primevideo is the main player website it seems.

Just wondering about Amazon Video again, with what I said, in the US there is no primevideo website, it goes through the main amazon website.

**Comment by lolamtisch** [comment]
@Hayatory 
It was already quite a headache to get it working on primevideo. The main Amazon page is even worse to possibly impossible. At least non of the main maintainers wants to try it. You will need to wait for a dev of the community, who wants to try it.

**Comment by henrik9999** [comment]
also im not really feeling the idea of the extension requiring access to amazon.com and therelike

**Comment by Hayatory** [comment]
> also im not really feeling the idea of the extension requiring access to amazon.com and therelike
True, that is understandable.
