### ISSUE TITLE
Any chance the menu at the bottom could be hidden completely?

### ISSUE THREAD

**Issue by Dyras** [lolamtisch/MALSync#298]
Greetings! I watch all my anime on Crunchyroll, with [Resize Video to Window Size](https://greasyfork.org/en/scripts/10815-resize-video-to-window-size). This makes the entire window fill up with the anime, which is great. Well, aside from the bottom where the gray MAL-Sync box is.

So I'm wondering, any chance you could add a setting to hide the gray part at the bottom entirely? Maybe just have it pop up if it's asking you about the right show?

Cheers for a great extension! Really helpful in keeping track of where I am in my shows.
![image](https://user-images.githubusercontent.com/12563436/73697056-f461fa80-46dd-11ea-9086-eab8e57a7660.png)

Apologies in advance if there's a setting for this and I couldn't find it.

**Comment by lolamtisch** [comment]
There is non atm. If I have time before the next release I will add it.

**Comment by lolamtisch** [comment]
With the release 0.7.0 it should dissappear when enabling the "stealth UI mode" in the settings
