### ISSUE TITLE
gogoanime.io problem with automatic anime sync

### ISSUE THREAD

**Issue by plW0lf** [lolamtisch/MALSync#299]
Error the same as in issue #251 - the error just returned - it doesn't automatically updates anime with video option enabled. (manual stil works). Already reinstalled userscript and used both with adblock on (which previously worked) and off.
**additional info**
- browser: chrome
- type: userscript
- url: https://www12.gogoanime.io/grisaia-no-kajitsu-episode-4

**Comment by lolamtisch** [comment]
I cant reproduce that problem. 

Does it work on other players? And does it work on other websites?

**Comment by plW0lf** [comment]
checked few players and it was the same. haven't checked on other websites.

**Comment by plW0lf** [comment]
Ok. So I can't skip endings otherwise I will skip 85% of video progress and anime won't update automatically.

**Comment by lolamtisch** [comment]
![Screenshot_20200209-110121__01](https://user-images.githubusercontent.com/12599334/74100133-a6108980-4b2b-11ea-8725-5ab9f43e1e71.jpg)
Normally 85% is enough. I never had a problem. But you can set it lower in the settings.

**Comment by lolamtisch** [comment]
Please reopen if still a problem
