### ISSUE TITLE
9 anime bookmark update? 

### ISSUE THREAD

**Issue by b1n4ryk1lla** [lolamtisch/MALSync#31]
is it possible to make it that 9anime bookmarks also reflect  MAL and vice versa so if something is set to watch list on mal its added to bookmark watch list on 9anime or if i complete an anime it sets the 9anime bookmark from watching to complete

**Comment by lolamtisch** [comment]
It is probably possible, but too much work to implement. Point of MAL-Sync is that you dont need the onsite bookmarks system as you have the links on MALs bookmarks. That is why i decided to remove support for onsite bookmarklists.

**Comment by b1n4ryk1lla** [comment]
agreed but the onsite bookmarks show up in kodi mal does not
