### ISSUE TITLE
Last episode and some UI not being shown

### ISSUE THREAD

**Issue by jb-99** [lolamtisch/MALSync#313]
This issue is occurring on [My Hero Academia](https://kissanime.ru/Anime/Boku-no-Hero-Academia-4th-Season) page on [kissanime](https://kissanime.ru/).  Last watched episode is not being shown as well as the UI at the bottom of the screen showing the next episode you haven't seen that you can click to get to it fast.

 Browser: Google Chrome
 Type: Extension
 URL: https://kissanime.ru/Anime/Boku-no-Hero-Academia-4th-Season

**Comment by lolamtisch** [comment]
I am not sure what you mean. Did you set the episode offset to `-63`? As kissanime starts with episode 64.

**Comment by jb-99** [comment]
I'm sorry I wasn't clear about what's happening.

After the latest update, My Hero Academia was particularly broken. Before the latest update, the episodes were somehow auto-detected and corrected but now they are not.

I've now set the offset to -63 and It's fine, it was just weird to me how it just stopped being detected.
