### ISSUE TITLE
mangalivre support

### ISSUE THREAD

**Issue by Hellscythe** [lolamtisch/MALSync#315]
add https://mangalivre.net/
biggest manga website in portuguese

**Comment by henrik9999** [comment]
We already support that

**Comment by henrik9999** [comment]
Maybe something on the site changed and broke it

**Comment by Hellscythe** [comment]
oh.... you can do something on these case? or thats all ?? :((( i use this as my main website now as many others closed and mal sync is a joy indispensable

**Comment by henrik9999** [comment]
Don't worry I'll look at it later

**Comment by Hellscythe** [comment]
thank youu ♥♥
