### ISSUE TITLE
Clicking "Cancel" on the "Rewatch anime" prompt causes rewatch

### ISSUE THREAD

**Issue by DarthSomebody** [lolamtisch/MALSync#32]
**Describe the bug**
When the "Rewatch anime" prompt appears and you click "Cancel", your MAL will be updated to the current episode.

**Steps to reproduce the behavior:**
1. Have a completed anime, let's say [Gintama Season 2](https://myanimelist.net/anime/9969/Gintama).
2. Go to an anime website and select an episode of [Gintama Season 2](https://www2.9anime.to/watch/gintama-season-2.7wkj/44n8k7). In 9anime's case, the anime page and the first episode of that anime is the same page, so even just going to the anime page will have the prompt triggered.
3. The "Rewatch anime" prompt will show up. Click "Cancel".
4. Your MAL is now updated to episode 1 of Gintama Season 2. 

**Additional information:**
- Browser: Firefox 64.0.2
- Type: Extension

**Comment by lolamtisch** [comment]
dont know why. But this issue did not show up until now. Already got fixed
