### ISSUE TITLE
AnimesHouse support

### ISSUE THREAD

**Issue by Hellscythe** [lolamtisch/MALSync#327]
https://animeshouse.net/
One of the most accessed anime websites in Brazil second Alexa rank still has no support to Mal Sync

**Comment by henrik9999** [comment]
Not possible because of how the site design is build

**Comment by henrik9999** [comment]
i found a way how to do it but it wont be the best stuff like ovas and specials wont work and there could be bugs here and there

**Comment by Hellscythe** [comment]
> i found a way how to do it but it wont be the best stuff like ovas and specials wont work and there could be bugs here and there

oh well... better than nothing... I was looking here and some others ppl said the same about this website with others extensions...

**Comment by lolamtisch** [comment]
Added in version 0.7.3
