### ISSUE TITLE
Add settings to disable/enable features

### ISSUE THREAD

**Issue by DarthSomebody** [lolamtisch/MALSync#33]
I never ever want to use the "rewatch anime" feature. It would be nice if we could get an option to disable/enable this separately for anime and manga.
It would also be nice if we could disable/enable tracking for anime and manga separately.

**Comment by lolamtisch** [comment]
I dont know why. But this issue did not show up until now. You can just untick the domains in the chrome settings if you dont want tracking on these.
![image](https://user-images.githubusercontent.com/12599334/62034672-ba73e100-b1ee-11e9-8395-a3c01e4ebf24.png)
