### ISSUE TITLE
Mal-Sync no longer works on AnimeUltima

### ISSUE THREAD

**Issue by IIZokuIX** [lolamtisch/MALSync#333]
Noticed AnimeUltima isn't even listed under streaming sites list as well. Could it be because they changed their url? (www1.animeultima.to)

**Comment by henrik9999** [comment]
its still listed there
we fixed it in the last release if you are on chrome and using the extension you have to wait form them to approve it

**Comment by IIZokuIX** [comment]
Ah okay, thank you.
