### ISSUE TITLE
Improve Popup for MAL Association

### ISSUE THREAD

**Issue by DarthSomebody** [lolamtisch/MALSync#336]
Whenever I check out a new manga that isn't linked to MAL yet, this huge popup opens right before I click the image to go to the next page. The result is that I accidently click on one of the options of the popup. This happens to me every single time it pops up. I'd rather have this popup only open iff I actually want to select a MAL entry for it, not if I only want to click through some pages to see what that manga is.

![image](https://user-images.githubusercontent.com/10331302/77533815-d91e9a80-6e97-11ea-9ccb-75ddf5838a83.png)

**Comment by lolamtisch** [comment]
I see your usecase. 
The popup only shows up if the script thinks it has a wrong mal entry. Removing the popup would only result in updates to wrong mal entries.

The only thing I could come up is to add an option to show the popup in a "minimized" way. Something like the start watching popup with a button to extend it to the full version. something like this. would that be enought?

![grafik](https://user-images.githubusercontent.com/12599334/77552852-56f09f00-6eb4-11ea-94c1-587416aba15a.png)

**Comment by DarthSomebody** [comment]
Yes, that would be great

**Comment by lolamtisch** [comment]
Is part of release 0.7.4 . The option is called "Minimize big pop-ups"

**Comment by DarthSomebody** [comment]
Thank you, works great!
