### ISSUE TITLE
Manga saving 2 times for different websites in local

### ISSUE THREAD

**Issue by RootAndroid58** [lolamtisch/MALSync#340]
**Describe the bug**
Some of the manga are not in mal so its saving locally but the issue is same manga watching from 2 or more than one different sites is making same name appear again and again.
_sry for bad english_

**Steps to reproduce the behavior:**
add these two manga to reading
https://mangadex.org/title/42718/the-descent-of-the-demonic-master
https://kissmanga.com/Manga/The-Descent-of-the-Demonic-Master
u will notice in the mal script that there are 2 names for same manga instead of showing 2 links in below .[image below shows different manga still u will get same results]

**Additional information:**
 - Browser:  chrome
 - Type:  userscript 
 - Url: -
 - image
![Capture](https://user-images.githubusercontent.com/28777412/77845477-e788f100-71cc-11ea-8909-b93015d20499.PNG)

**Comment by lolamtisch** [comment]
As I have no relation to Mal or something else I can't recognise that the entry is already on the list. 
Checking if the title is the same is no solution because of #165 . 
You will need to delete the other entry by hand.
