### ISSUE TITLE
Auto change from anime to manga

### ISSUE THREAD

**Issue by RootAndroid58** [lolamtisch/MALSync#341]
sometimes in userscript when i directly open the anime page by clicking the button and go to home from there it sends to anime instead of going to manga

**Comment by lolamtisch** [comment]
I can't follow. What do you mean?

**Comment by RootAndroid58** [comment]
lets say i opened a manga in new page like opening link in new fresh page 
then when u open the mal userscript and go to home u will go to anime instead of going to manga

**Comment by RootAndroid58** [comment]
see this gif 



![VID_20200331_200611](https://user-images.githubusercontent.com/28777412/78044902-e86b7f80-7392-11ea-9252-2dae6101c7bc.gif)

**Comment by lolamtisch** [comment]
I understand now what you mean. I will look into it. 

But it wont work for mangas that are not on mal for the popup, but in the onsite popover it will work.

**Comment by RootAndroid58** [comment]
> But it wont work for mangas that are not on mal for the popup, but in the onsite popover it will work.

you mean the userscript right if that's the case then i will simply enable the ETC userscript mode

**Comment by lolamtisch** [comment]
No i mean in the gif you have an manga open that has no mal entry and is saved in localstorage. As the popup is in a different screen it cant easily access that data. But for normal mangas with mal entry it will work

**Comment by lolamtisch** [comment]
Added
