### ISSUE TITLE
[MAL] Server Offline

### ISSUE THREAD

**Issue by namv22** [lolamtisch/MALSync#343]
**Describe the bug**
When I see a new manga and press the Add too MAL, a small popup appear and says: [MAL] Server Offline
I went to MAL and saw that it's still online and working as usual
Here are some pictures I took on MangaNelo and Mangapark

[MangaPark](https://photos.app.goo.gl/LEDCjiZpMkahBKgA7)
[MangaNelo](https://photos.app.goo.gl/J6CH3kgQX4VJWjsJA)

**Steps to reproduce the behavior:**
1. Go to a manga page that has not been added to MAL yet
2. Click Add to MAL

**Additional information:**
 - Browser: Opera GX version is LVL 1 (core: 67.0.3575.105)
 - Type: I use MAL-sync extension
 - Url:

**Comment by henrik9999** [comment]
Yeah it's an bug will be fixed in the next release until then I wouldn't recommend you to add the manga manually

**Comment by namv22** [comment]
> Yeah it's an bug will be fixed in the next release until then I would recommend you to add the manga manually since it only happens when the manga hasn't been added to your list yet

ok thanks, I'll wait then

**Comment by lolamtisch** [comment]
Should now be fixed with release 0.7.4

**Comment by namv22** [comment]
since it's fix, I will now close this
