### ISSUE TITLE
Blank Anime Entry on MyAnimeList's Seasonal Anime Web Pages

### ISSUE THREAD

**Issue by APrasad021** [lolamtisch/MALSync#35]
**Describe the bug**
When the extension is opened on any seasonal anime page off of MAL (url ends with /anime/season/*), it shows a page with no information. A user can try to add a nonexistent anime named "anime database" to their MAL. Rather than that, the extension should display the user's anime list/the seasonal anime in the extension. 

This is what the extension looks like when it is opened on a seasonal anime page off of MAL.
![Blank MALSync Extension](https://user-images.githubusercontent.com/14186569/52028083-aff4bb00-24db-11e9-8239-76bbd9667562.png)

This is what happens when I try to update my MAL via the blank item in the extension.
![screen shot 2019-01-30 at 9 57 07 pm](https://user-images.githubusercontent.com/14186569/52028122-d4e92e00-24db-11e9-9cb8-74ceca8b46d4.png)

**Steps to reproduce the behavior:**
Open the extension on any page seasonal anime (url begins with [https://myanimelist.net/anime/season](https://myanimelist.net/anime/season)). You can then try to update your MAL via MALSync, which will return an "update failed."

**Additional information:**
 - Browser: Chrome
 - Type: Extension
 - Url: [https://myanimelist.net/anime/season(/*)](https://myanimelist.net/anime/season)

**Comment by lolamtisch** [comment]
Thanks for letting me know. Will be fixed with the next release.
