### ISSUE TITLE
Mark episode as read/watched shortcut

### ISSUE THREAD

**Issue by plW0lf** [lolamtisch/MALSync#351]
As there is no option to automatically mark manga episode as completed, It would be great if configurable keyboard shortcut for it would be added.

Edit: I meant automatically marking manga episode as completed by detecting last page. :)

**Comment by lolamtisch** [comment]
Unfortunatly it is difficult to implement. Because every website has a different reader with different mody and some use custom reader. It could be added, but probably not in the near future.

Shortcut support should not be a problem.

**Comment by lolamtisch** [comment]
Shortcut added. 'Set episode/chapter as read'
