### ISSUE TITLE
MAL review profile images resized incorrectly

### ISSUE THREAD

**Issue by krackers** [lolamtisch/MALSync#355]
**Describe the bug**
With the extension enabled, the profile pictures on reviews on MAL are much larger than they should be. The issue seems to be related to the injected css from
https://github.com/lolamtisch/MALSync/blob/6d35634d5152bacf1676a0f83a702dea24bf5aea/src/myanimelist/myanimelistClass.ts#L111

since the profile images have `.Kal` which causes the width to be set to `width: auto !important;` whereas normally the width is ~48px or so.

**Steps to reproduce the behavior:**
Navigate to review section on any MAL page, profile pictures of reviewers are much larger than they should be

**Additional information:**
 - Browser:  Chrome
 - Type: Extension

**Comment by henrik9999** [comment]
You can disable this behavior in the settings

**Comment by henrik9999** [comment]
Yeah looks like MAL changed something again

**Comment by lolamtisch** [comment]
Yeah they changed something. You can set the thumbnail option to mal default until it gets fixed in the next release.
