### ISSUE TITLE
Wonderfulsubs not tracking watched

### ISSUE THREAD

**Issue by b1n4ryk1lla** [lolamtisch/MALSync#357]
**Describe the bug**
watched episodes not being tracked
**Steps to reproduce the behavior:**
https://beta.wonderfulsubs.com/watch/codegeasslelouchoftherebellion?ss=0&e=2
**Additional information:**
 - Browser: Chrome 81.0.4044.92 (Official Build) (64-bit)

 - Type: version 0.7.4 
 - Site: beta.wonderfulsubs.com

**Comment by henrik9999** [comment]
wonderful subs got removed due to request of the owner
