### ISSUE TITLE
Showing MAL Entries on twist.moe Search

### ISSUE THREAD

**Issue by APrasad021** [lolamtisch/MALSync#36]
On twist.moe, the search bar essentially shows all the anime in their db. As you type characters, the query narrows. Sometimes, there are a lot of titles that pop up, so it would be nice to have some distinction on anime that are in my own MAL. 

Something like this is what I was thinking of. Twist.moe already has "ONGOING" elements on the right of airing anime.
![animeee](https://user-images.githubusercontent.com/14186569/52083307-14ac2600-256d-11e9-8faa-ab220085d942.PNG)

Something like this could also be implemented on other websites too.

**Comment by lolamtisch** [comment]
I dont want to add onsite implementations like that anymore. Because throw the links on MALs bookmarks list I see no need anymore.

**Comment by APrasad021** [comment]
That's fair. Performance wise, you may be right with it being expensive, especially if someone has a long list. If you were to implement this, it may be good to just add elements for watching (and maybe plan to watch), but I wasn't sure how difficult it would be to implement when I suggested it.
