### ISSUE TITLE
Masterani.me 'Continue watching' link instead of 'Resume watching'

### ISSUE THREAD

**Issue by HyperEpsilon** [lolamtisch/MALSync#37]
**Describe the bug**
When I've watched all the available episodes of a show on KissAnime typically a 'Resume watching' link replaces the 'Continue watching' link. However, since switching to masterani.me I've noticed that instead the icon stays as continue watching despite redirecting to the info page instead.

**Steps to reproduce the behavior:**
Watch all available episodes of any currently airing show on masterani.me, check MAL badge

**Additional information:**
 - Browser: Chrome
 - Type: Extension v0.4.3
 - Url: https://puu.sh/CI8m0/de83b35e46.jpg

**Comment by lolamtisch** [comment]
Fixed in release 0.4.4
