### ISSUE TITLE
Add Support for Emby Server

### ISSUE THREAD

**Issue by brassica77** [lolamtisch/MALSync#39]
Hi,
Can you please add support to [Emby Server](https://emby.media), with a plugin similar to Emby's [Trakt](https://github.com/MediaBrowser/trakt) one, maybe using something like the [Kitsu](https://github.com/hummingbird-me/kitsu-tools) workaround to bypass the MAL API current situation?

[malsync.user.js.txt](https://github.com/lolamtisch/MALSync/files/2920673/malsync.user.js.txt)

**Comment by lolamtisch** [comment]
![image](https://user-images.githubusercontent.com/12599334/53696534-2c730600-3dc8-11e9-8b48-43e560dd64cc.png)

**Comment by lolamtisch** [comment]
Ver2
Supports the season page now too. But you have to open any video first so that it can get the needed autentificartion data for it to work on the season page.
[malsync.user.js.txt](https://github.com/lolamtisch/MALSync/files/2923359/malsync.user.js.txt)
