### ISSUE TITLE
less options in miniMAL settings compared to KissAnimeList

### ISSUE THREAD

**Issue by Eskander** [lolamtisch/MALSync#4]
Please add back the switch that disables the whole "Next episode estimated in" thing, and probably the other switches that used to be in KAL settings.

Also it's not clear (to me at least) what does this switch enable/disable exactly.

![image](https://user-images.githubusercontent.com/11521400/46702891-d042f600-cc1c-11e8-8ab2-4b770bd85022.png)

I believe adding a (!) popup for that option too would be helpful. Thanks

**Comment by lolamtisch** [comment]
@Eskander 
The "Next episode estimated in" will be part of the next Release.
The "MAL Tags" option is the  "Continue watching links" of KAL. I think i will rename it to that again to make it clearer.

**Comment by quietlystorming** [comment]
Hi,

I would add to this, the autotracker delay seems to be missing? Please re-add if this feature was removed.

**Comment by Eskander** [comment]
@lolamtisch I'm not seeing the "Continue watching" links with "MAL Tags" enabled/disabled. Where should I see them, at MAL bookmarks? At the streaming site? At the anime page on MAL?

**Comment by Eskander** [comment]
I see now, after some experimentation I was missing the auto updating part, seems KAL tags aren't compatible with MALSync. But even with "Mal tags" switched off I still get "Continue watching" links

**Comment by lolamtisch** [comment]
Options are added in version 0.2.7

**Comment by Eskander** [comment]
@lolamtisch It is good to hear 🎉 But the issue I reported above

> But even with "Mal tags" switched off I still get "Continue watching" links

is still occurring with the renamed "Continue watching links". Should I open a separate Issue for it?

**Comment by lolamtisch** [comment]
Busy atm, will look into it in the next few days.

**Comment by lolamtisch** [comment]
The option should now work like that
