### ISSUE TITLE
Add support for Kitsu

### ISSUE THREAD

**Issue by brassica77** [lolamtisch/MALSync#41]
Hi,
Can you please add support for Kitsu in your extension?
You can find the API documentation [here](https://kitsu.docs.apiary.io/#)

**Comment by lolamtisch** [comment]
Password Grant is the only autentication type atm. So I would need to handle username and password on my side. Not the biggest fan of that. 

Looks like they dont want give out the mal id for animes. Only for people and character?? One can only find kitsu animes with the mal id, but not the other way around. My complete mapping database work over the malid.

The database correction process looks like a pain too, specialy as you cant check the malid.

I am going to add it for sure, but not in the near Future.

**Comment by matthewdias** [comment]
@lolamtisch you can get the mal id via the mappings resource https://kitsu.docs.apiary.io/#reference/media/mappings

**Comment by lolamtisch** [comment]
Added in release 0.4.9
