### ISSUE TITLE
"Update Failed' error on 9anime

### ISSUE THREAD

**Issue by hemlok89** [lolamtisch/MALSync#42]
I am experiencing an Update Failed notice only on 9anime. Whether opening an anime directly in 9anime or redirecting from MAL. Other sites, GoGo Anime, or KA is working fine. Also the MiniMAL is not working on 9anime. Here is a [screenshot](https://i.imgur.com/0dK975n.png).

Here is the [console output](https://i.imgur.com/HwK5ojd.png).

Here is the console output in [text](https://pastebin.com/MLD1p0Fx)

**Additional information:**
 - Browser: Firefox 65.0.2
 - Type: Userscript

**Comment by hemlok89** [comment]
Here is the the console output in [text](https://pastebin.com/MLD1p0Fx)

**Comment by lolamtisch** [comment]
@hemlok89 
Is it for all anime on 9anime? Works on my side.

Did you try this already from the troubleshooting page?
### Updating myanimelist entry fails
Data could be corrupt throw another sync utilities. Please remove it from Mal and re add it.

**Comment by Karmesinrot** [comment]
@hemlok89 
It is caused by a ublock filter which only affects the stable version of Firefox add this `9anime.ru,9anime.to#@#+js(set-constant.js, String.prototype.charAt, trueFunc)` to your filters or subscribe to `https://raw.githubusercontent.com/Karmesinrot/Anifiltrs/master/Anifltrs.txt`

**Comment by hemlok89** [comment]
Thank you @Karmesinrot this worked. I am already subscribed to your filter. I think it hasn't been updated in a while.
