### ISSUE TITLE
Ability to Retrieve Manga Data From AniList Apart From MAL

### ISSUE THREAD

**Issue by DelKatey** [lolamtisch/MALSync#48]
Hi, I have noticed that on numerous times, there may be a manga title that is already on AniList, but not on MAL. There are almost no instances, however, that I have encountered where both MAL and AniList lacks the title.

When the title exists on AniList but not MAL, the app is not able to track the manga and chapters read, as a consequence of that.

Therefore, is there a possibility of the app retrieving info for the manga from AniList directly as well, when in AniList mode?

**Comment by lolamtisch** [comment]
@DelKatey 
![image](https://user-images.githubusercontent.com/12599334/54953881-91de9080-4f49-11e9-8b91-4ca41ae2abe2.png)
You can enter here the anilist url and the tracking will atleast work. That is the current workaround
