### ISSUE TITLE
More integration for Anilist

### ISSUE THREAD

**Issue by hemlok89** [lolamtisch/MALSync#50]
Hello, 

I saw an latest issue #48 & I would like this script have more integration with AniList. MAL has an weird verification process, thus many new manga & manhwa are not found on MAL. But Anilist generally have them. I have set the mode to Anilist & it would be better to pull data from Anilist rather than MAL. The review & recommendation system is much better on MAL, so no problem there.

**Comment by lolamtisch** [comment]
I never had anilist in mind during development. So many things rely on the MAL id. Specifically in miniMAL. It is only appearend on a small number of edge cases, that is why I postponed it. But it will come.

**Comment by lolamtisch** [comment]
@hemlok89 
Search and overview metadata in miniMAL is now retrived from anilist/kitsu.

**Comment by lolamtisch** [comment]
The search system uses anilist for mappings too now. I think with this anilist is as far integrated as possible.

**Comment by hemlok89** [comment]
Thank you! Yes, this is more than expected.
