### ISSUE TITLE
Kitsu Authentication error

### ISSUE THREAD

**Issue by hemlok89** [lolamtisch/MALSync#52]
I just tried out the new Kitsu implementation. On the authentication page, it is showing some error. Here is a [screenshot](https://i.imgur.com/Dt7fLAB.png)

Browser: Chrome
Type: Userscript

**Comment by lolamtisch** [comment]
@hemlok89 
Kitsu changed the error message format again? But that is the error message if the credentials are wrong. Are you sure they are correct? Btw Facebook login is not supported.

**Comment by hemlok89** [comment]
No, credentials are right. I am actually [logged in](https://i.imgur.com/s3S44sp.png).

And no, I have an account, not facebook login.

**Comment by hemlok89** [comment]
BTW, this is the console log of the authentication page. My UBO is turned off just in case.

https://pastebin.com/3aHd2xBc

**Comment by lolamtisch** [comment]
Looks like there is an error 'Cannot read property 'toUpperCase' of undefined'. Could you screenshot the code behind the error. Because the line info is different from device to device I think.
I could not reproduce the error on my side.
Some other things you could try:
Change your password to something simple.
Try out the extension.

**Comment by hemlok89** [comment]
Ok, changing the password to only 6 letter (alphabet only) worked & I got this [screen](https://i.imgur.com/905H6lP.png).

The error I was getting were [Pic1](https://i.imgur.com/8FvSGer.png) & [Pic2](https://i.imgur.com/kQLpZHj.png).

But even after getting the token, setting on [Kitsu mode](https://i.imgur.com/5HDbu4s.png) is not detecting any episodes. I guess the token is not registering. Also manually setting an anime to watching [updates it to MAL](https://i.imgur.com/MYXfjaJ.png).

By the way, my previous password was 1h*9%h&aOZYK. I think there might be a problem with character limit or symbols.

**Comment by lolamtisch** [comment]
I had to encode the password before sending. The & was breaking it. 

Did you reload the page? The data is not changed instantly. I really should add some messages there.

**Comment by hemlok89** [comment]
I just checked again right now. I opened an unwatched anime on GoGoanime. When in MAL mode, the top bar appears to start watching. I then changed the mode to Kitsu. First, there was no header bar. I authenticated again & reload the page to make the top bar appear. But the mini MAL is displaying information from MAL even in Kitsu mode. Here is a [screenshot](https://i.imgur.com/ctFqry3.png).

**Comment by hemlok89** [comment]
I cleared cache of MAL sync & tried again. Tested on some other animes. Some times it displays information from MAL if the anime is in my MAL list. But overall I got it to working in Kitsu mode & successfully added an anime via MAL sync to kitsu.

**Comment by lolamtisch** [comment]
MiniMAL displays the text images allways from MAL. But it is impossible that it shows the episode number and animelist from your mal list.
