### ISSUE TITLE
Masteranime incorrect page (all anime)

### ISSUE THREAD

**Issue by Elfshot** [lolamtisch/MALSync#7]
Using either of these two buttons takes me to the incorrect masteranime page
![image](https://user-images.githubusercontent.com/44043197/46773823-659dc300-cccd-11e8-9996-9e1eab3a0c68.png)
![image](https://user-images.githubusercontent.com/44043197/46773826-6cc4d100-cccd-11e8-8bf4-93e6b5ce75b6.png)

This is the URL and error page.
https://www.masterani.me/anime/watch/2918-banana-fish
![image](https://user-images.githubusercontent.com/44043197/46773839-81a16480-cccd-11e8-9381-fa0d089f4b5e.png)

It's just a slight issue, in the URL 'watch' is supposed to be info (/anime/watch/2918)

correct URL and page
https://www.masterani.me/anime/info/2918-banana-fish
![image](https://user-images.githubusercontent.com/44043197/46773885-b4e3f380-cccd-11e8-91e4-3ead56b22780.png)

**Comment by lolamtisch** [comment]
1. Don't use kissanimelist and MAL-sync at the same time. Please disable kissanimelist.

After that could you let it sync a episode again( it has to autoincrement the episode once) and check if that solves the problem?

**Comment by Elfshot** [comment]
the issue is fixed but only for the anime that have a continue icon (with exception of Tokyo Ghoul re: 2nd)
![image](https://user-images.githubusercontent.com/44043197/46832567-62114700-cd74-11e8-894f-ff85d6b5de0e.png)


whereas anime without the continue icon and only a masteranime icon the issue persists  
![image](https://user-images.githubusercontent.com/44043197/46832611-7fdeac00-cd74-11e8-959d-a916ed21d668.png)

**Comment by lolamtisch** [comment]
The url is saved on your MAL account. That means you have to autotrack it once per series so it gets updated. If you think you did it right and it is still wrong, could you open the detailed anime update page on Mal and send me the content of the tag field.

**Comment by Elfshot** [comment]
it seems i have to wait for a new episode of all my anime and have it autotrack each one before the icon starts working, thanks
