### ISSUE TITLE
bookmark question

### ISSUE THREAD

**Issue by stapuft** [lolamtisch/MALSync#72]
I know you said it was too much trouble to implement bookmark sync but what about this, adding a button that adds an anime to your mal list in the hover info window
![image](https://user-images.githubusercontent.com/46431157/56567441-ed209480-6582-11e9-93d4-c05067d9ec09.png)
the button there now adds the item to your 9anime bookmarks, if you have an account there, I am suggesting a second one, like what is on the anime page, but in the hover window.

**Comment by lolamtisch** [comment]
Currently I want to keep my distance from page specific implementations. It would be a lot of work too only for an minor convenience feature. Closing the Issue for now.

**Comment by stapuft** [comment]
its not really minor at all though, and loads of anime sites have those hoverinfo boxes, but I guess I get you you want more universal stuff...... @lolamtisch what about an option to make it auto enter fullscreen when playing an episode? that is a rather universal application. I just added that feature to my keyboard shortcuts superscript with this small bit of code

```
var elem = document.getElementsByTagName("video")[0];
if (elem.requestFullscreen) {
  elem.requestFullscreen();
} else if (elem.msRequestFullscreen) {
  elem.msRequestFullscreen();
} else if (elem.mozRequestFullScreen) {
  elem.mozRequestFullScreen();
} else if (elem.webkitRequestFullscreen) {
  elem.webkitRequestFullscreen();
}

```

I'm just trying to show my support for you and your amazing project, I know I'm a newb when it comes to coding, but i still like to try.
