### ISSUE TITLE
AutoFullscreen

### ISSUE THREAD

**Issue by lolamtisch** [lolamtisch/MALSync#76]
@lolamtisch what about an option to make it auto enter fullscreen when playing an episode? that is a rather universal application. I just added that feature to my keyboard shortcuts userscript with this small bit of code

```
var elem = document.getElementsByTagName("video")[0];
if (elem.requestFullscreen) {
  elem.requestFullscreen();
} else if (elem.msRequestFullscreen) {
  elem.msRequestFullscreen();
} else if (elem.mozRequestFullScreen) {
  elem.mozRequestFullScreen();
} else if (elem.webkitRequestFullscreen) {
  elem.webkitRequestFullscreen();
}

```

I'm just trying to show my support for you and your amazing project, I know I'm a newb when it comes to coding, but i still like to try.

_Originally posted by @stapuft in https://github.com/lolamtisch/MALSync/issues/72#issuecomment-486005357_

**Comment by lolamtisch** [comment]
@stapuft
Cool Idea. First tests look promising. Will look into it further soon.

**Comment by stapuft** [comment]
:D yea! im glad i could help add a feature to the project!!
