### ISSUE TITLE
Kitsu Manhwa not getting updated

### ISSUE THREAD

**Issue by nishantjulian** [lolamtisch/MALSync#77]
**Describe the bug**

1. Manhwa's Kitsu url is not getting updated.
2. Manhwa chapters, if added manually, does not get updated automatically while reading.
3. The manhwa titles are not being shown in the bookmarks tab.

**Steps to reproduce the behavior:**

1. Set Mode : Kitsu in settings and Authenticate

2. Visit mangarock's Manhwa page, example 'Don's Adventure in Another World' and read any chapter
link- https://mangarock.com/manga/mrs-serie-100084218/chapter/mrs-chapter-200032610
a. The prompt asking the status of the manga is not showing up.

3. Add the manhwa manually to MAL-sync using the settings page and enter the kitsu url.
link- https://kitsu.io/manga/dons-adventure-in-another-world

4. Click on update and wait. A prompt saying 'New Url Set' is displayed
a. URL is set but the chapters are still not updated

5. Click on Bookmarks tab
a. The Manhwa is added to the Reading Manga section, but the ' Title' and 'Chapter' is not displayed.

**Additional information:**

 - Browser: Chrome
 - Mode: Kitsu and Authenticated (It still always show the Authentication link though)
 - Url: https://mangarock.com/manga/mrs-serie-100084218
 - Url: https://kitsu.io/manga/dons-adventure-in-another-world

PS-
I am using 'Mode: Kitsu' to sync both Manga and Webtoons with Kitsu. As Kitsu has Export to MAL settings.

<img width="1173" alt="Screenshot 2019-05-03 at 4 35 53 PM" src="https://user-images.githubusercontent.com/23497194/57135104-ee915e80-6dc5-11e9-8ad3-e3d3c259d7e0.png">
<img width="1440" alt="Screenshot 2019-05-03 at 4 36 30 PM" src="https://user-images.githubusercontent.com/23497194/57135110-f0f3b880-6dc5-11e9-80b1-57aa28690327.png">

**Comment by lolamtisch** [comment]
Should be fixed with version 0.4.17
