### ISSUE TITLE
auto fullscreen controlls

### ISSUE THREAD

**Issue by stapuft** [lolamtisch/MALSync#82]
I disabled my auto fullscreen userscript to test out the one I suggested be put into Mal, I don't know if you used the code I suggested or not but it works, feel free to canabalize it to your will, 
https://github.com/stapuft/anime-couch-mode-activator/blob/master/anime%20couch%20mode%20activator-pard%20deux.user.js
(yes that crappy code took me a few weeks, I couldnt figure out how to make the control bar disapear automatically AND appear when you moved the mouse or hit a keyboard shortcut, that is what took me a while, I'm still new to this and don't really know much....who knew I could just tell it to simulate a mouse click with .click.....i should have...but i didn't...)

but I had a few issues with it mal-sync today,  it didnt want to work at first, but after a few page refreshes it worked, I got no clue if i was just inpatient or what. but the main issue appears to be the controls. they do not appear, at all, in fullscreen, it took me a bit to get over that, and I never managed to get the original controls but with these two lnes
```


document.getElementsByTagName("video")[0].setAttribute("controls","controls");

document.getElementsByTagName("video")[0].click(("video")[0]);

```

I managed to make the native Firefox controls appear, and auto disappear, I know my code is shit but you can make it far better hell you could probably figure out how to show the normal ones probably. because I just checked your code for this and it is FAR superior to mine you got all the contingencies on lock for that so I know you can do this too man!

**Comment by stapuft** [comment]
var playerEl = player;

    var ids = [
      'player',
      'vstr',
      'vplayer',
      'mgvideo',
      'myVideo',
      'b-video-wrapper',
    ];

    var classes = [
      'AT-player',
      'plyr',
      'AkiraPlayer',
];

possibly it has something to do with the player id/class?

here is the class of the player from kissanime
class="video-js vjs-default-skin vjs-big-play-centered vjs-controls-enabled vjs-has-started vjs-paused vjs-user-inactive

i got no clue I'm sorry if I'm not helping any.

**Comment by lolamtisch** [comment]
I played around with the controls attribute earlier, but on chrome apparently it has no effect. So i thought it does nothing. 
I added it to the fallback if no class/id is found. 👍

**Comment by stapuft** [comment]
like I said, I'm still new at this and stuff, but somehow that makes it work, ou rule man!

did you go to college for this? or are you self taught?

**Comment by lolamtisch** [comment]
@stapuft
Here is not the right place to ask.😉 Just drop by on my discord server for that.
https://discordapp.com/invite/cTH4yaw

**Comment by lolamtisch** [comment]
release 0.5.0 should contain it now
