### ISSUE TITLE
9anime new domain

### ISSUE THREAD

**Issue by Ev3X** [lolamtisch/MALSync#83]
**MAL Sync is not working as 9anime added new proxy for those where 9anime.to cannot be accessed**
New proxy. Its now 9anime.nl. Please add this new proxy/domain to the extension and userscript please.

**Thank you**

**Additional information:**
 - Browser: Chrome
 - Type: Extension & Userscript both
 - Url: https://9anime.nl/home

**Comment by lolamtisch** [comment]
@Ev3X 
Are you sure you have have the newsest version installed? I already added that domain some releases ago.

**Comment by Ev3X** [comment]
> @Ev3X
> Are you sure you have have the newsest version installed? I already added that domain some releases ago.

yeah, I reinstalled it, it's working fine now. Thank you 

Also, before, during each episode, at the bottom of the page, info/synopsis of the episode popped up when you go to it, now not anymore. Did you get rid of it?

**Comment by lolamtisch** [comment]
@Ev3X 
Yes i got rid of it since the MAL-Sync rewrite, because the implementation was very messy. I am not sure if i am going to re add it, because the popup is already complex enought.
