### ISSUE TITLE
English titles [feature request]

### ISSUE THREAD

**Issue by stapuft** [lolamtisch/MALSync#87]
but whenever malsync asks "is *blank* the correct anime" I always have to use Google to see if it is indeed the right anime, is there anyway to change the Japanese (romanji) title usage to the actual English title?

example
Kono Yo no Hate de Koi wo Utau Shoujo YU-NO=Japanese (romanji) title
YU-NO: A girl who chants love at the bound of this world.=actual English title

Hokuto no ken=Japanese (romanji) title
fist of the north star=actual English title

boku no hero academia=Japanese (romanji) title (the only one I really don't have to Google imo)
my hero academia=actual English title

**Comment by Karmesinrot** [comment]
It's not really a bug, more like a feature request for a toggle switch for English title . MAL-Sync uses the Japanese (romanji) title since that is what MyAnimeList/Anilist/Kitsu uses.

**Comment by stapuft** [comment]
okay thank for clearing that up for me.

**Comment by lolamtisch** [comment]
* MAL
Unfortulaty there is only that one title on the page that I have to use: https://myanimelist.net/ownlist/anime/add?selected_series_id=34620
I think it does not justifiy an extra call to a much bigger site, just to get a different title.
Workaround: You can just open miniMAL it shows the alternative titles. Fast and easy.
![image](https://user-images.githubusercontent.com/12599334/58315251-7d1b5d80-7e11-11e9-9f6d-d4f3396701f1.png)
Fututre: I only see it fixed when mal gets the new api released. 
Or if I decide to switch to an unofficial api (Unlikely for now)

* Anilist
Uses the title type set in the profile options

* kitsu 
En -> romaji -> jp

**Comment by stapuft** [comment]
what do you mean? every show on m,AL has like 3 titles, and you just showed a picture that shows a clear example? there is no need for a call to a bigger site when that site has all you need, all you would have to do would be to have the main title be the actual English one. (though I honestly do not know the Mal api at all it should be labeled in there just like on the site? which would make for a simple substitution of the romanji text for the English text...though if its not things could be harder....)
i mena the correct title is even labeled with "English" on MAL though for some reason its in the "alternate titles" section of the page.
![image](https://user-images.githubusercontent.com/46431157/58345571-b1e5df80-7e26-11e9-90ca-1d4b34b8b543.png)


anilist/kitsu actually use the right titles? yet another reason to switch to them.....is there a way to switch my MAL stuff over to one of them? im getting real tired of MAL nad its eliteism.......

**Comment by lolamtisch** [comment]
There is no English title in the URL that I sent you.
https://myanimelist.net/ownlist/anime/add?selected_series_id=34620
Blocked(blocker) means that it is dependent on something that I have no influence over. Here the Mal API. It has first be done until I can do anything about it. It doesn't change the visibility.

**Comment by lolamtisch** [comment]
For futher clarification:
Mal has currently no api. What mal-sync does atm is loading the website in the background and live scrapping all the needed info. That is why i can only work with the info that I get.
That is no problem witht the kitsu/anilist apis, even if kitsu´s api does not allways works like it should.

**Comment by stapuft** [comment]
okay so since there is no api atm, why not just load the other page for the anime, and not that one? would it be too much of a memory hog or something?
