### ISSUE TITLE
UI color change issue with Mangarock website

### ISSUE THREAD

**Issue by nishantjulian** [lolamtisch/MALSync#88]
**Describe the bug**
Colour changes happening in the source website mangarock.com with the colour scheme used in MAL-sync extension. The colour changes go back to normal when the extension is disabled.

Webpage with the bug-
![Manga Rock Home Page](https://user-images.githubusercontent.com/23497194/58316850-2b36ff80-7e32-11e9-8eee-1266eb45b6cc.png)

![My Hero Academia](https://user-images.githubusercontent.com/23497194/58316874-39851b80-7e32-11e9-929a-00aa5bcffb22.png)

Webpage without bug-
![Manga Rock   Online Manga Reader](https://user-images.githubusercontent.com/23497194/58316930-5883ad80-7e32-11e9-8ad5-25ecb8145511.png)

**Steps to reproduce the behaviour:**
1. Add MAL-sync extension
2. Visit [mangarock.com](https://mangarock.com/) 
_The colour changes are visible_
3. Visit any manga description page,e.g., [Black Clover](https://mangarock.com/manga/mrs-serie-28856)
_The colour changes are visible_

**Additional information:**
 - Browser: Chrome
 - Type: Extension
 - Url: [https://mangarock.com/](https://mangarock.com/)

**Comment by lolamtisch** [comment]
Thank you for letting me know. 
This happened because some styles that are for the miniMAL frame got wrongly loaded into the main page. This is a bug and will be fixed with the next release.

**Comment by lolamtisch** [comment]
Should be fixed in 0.5.1
