### ISSUE TITLE
neither anilist or kitsu will authenticate 

### ISSUE THREAD

**Issue by stapuft** [lolamtisch/MALSync#89]
I just made both an anilist and a kitsu account and imported my MAL list into them, I authenticated malsync for each on their respective websites, and when I change the malsync settings to either kitsu or animist, it asks me to authenticate again, I do, but nothing changes, the message telling me I can close the page because the token has been saved comes up, but it never actually authenticates.

**Comment by stapuft** [comment]
i have debugged the extension and went to the location where the keys are supposed to be stored, but they are both blank, and the debug console will not let me edit the keys that I snatched from the console window on the authentication page, into the location where they are meant to be stored???

help me @lolamtisch you are me only hope!

**Comment by lolamtisch** [comment]
1. Make sure MAL-sync only is loaded once. (Disable userscript/selfbuild dev extension)

2. Clear all the cache in the miniMAL settings. It solved the problem once. No idea why.

3. Reload all the tabs after setting the token

4. Restart everything ¯\\_(ツ)_/¯

There is no complex code there. So no idea what could be the problem. I think it has something to be with the browser having problems saving to the sync storage.

PS: Sorry sometimes I miss emails. I normaly responde faster and more frequently on discord.

**Comment by stapuft** [comment]
OK after doing all that and restarting multiple times its finally syncing, even though malsync still says it needs to be authenticated, its syncing my watch history with kitsu no problem??

ive been having multiple computer issues as of lately, the latest windows updates aren't as stable as they should be, something is gobbling up my memory like crazy.

its cool thanks for all the hard work you do for us.
