### ISSUE TITLE
Video skipping

### ISSUE THREAD

**Issue by Reawy** [lolamtisch/MALSync#95]
**Describe the bug**

At close to the end of episodes of an show I have already watched it auto-skipping forward to where I closed the video of the last time I watched it.

**Steps to reproduce the behavior:**

Watch an episode and close tab reopen it so you get the top box with the resume at time.
![GS 2019-06-02 01_56_42](https://user-images.githubusercontent.com/51276884/58755191-b2454100-84de-11e9-905f-8a264296dd9f.png)
Ignore it and then when you watch that episode from start (Not sure if its at the time the extension checks "Update on 85% of video progress" then I think it skips to the time you closed the tab last time you watched that episode).
I think it happens 100% of the time also tested with an episode I have not watched and it doesn't skip.

**Additional information:**
 - Browser: Chrome Version 74.0.3729.169 (Official Build) (64-bit)
 - Type: Extension
 - Url: https://www1.9anime.nl/home

**Comment by lolamtisch** [comment]
I am not sure what you mean.
What I tried:
1. Open video around 20 min
2. Reload page
3. The resume box appears
4. Close it
The Video is already on the beginning for me? I waited a few minutes. Nothing happened

If you mean that it auto reloads the timestamp on load, then it is mostl likely a feature that is already build in into the player and not something my extension does. MyCloud for example does it.

**Comment by Reawy** [comment]
When it happens to me its when I watch an show to its end and after that when I rewatch that show all episodes are remembered with the resume time button. So when I rewatch those episodes and when the time of the video comes to a certain time my guess is when the extension checks "Update on 85% of video progress" it automatically skips the video to the time when I closed that episode the last time I watch that episode.

So for an example I watch a show that is 24 minutes long and it will register episode as watched at 20m24s  (85%) as intended but the episode is not done so I watch until 22m30s usually when the animes ED is playing. So when I come back to rewatch that show it remembers the last time I watched it "Resume at 22:30" so I just ignore that and full-screen and when the video comes to the time when the extension registers episode as watched at 20m24s (85%) it skips forward to the time when I closed the show last time I watched that episode at 22m30s.

I also think it only happens if the extension can register that episode to MAL so I don't think you can just reload the page I think you need to ether remove it from MAL or set it as "Re-watching". I have tested to set MAL-Sync "Anime sync" setting to manual and instant that seems to not skip anymore.

I'm not a native English speaker so its possible my explanation is not coming out as I intend.

**Comment by lolamtisch** [comment]
I was able to reproduce it. Will be fixed in the next release. 

Another workaround if you want to keep the video sync enabled is to make sure you close the resume popup before watching.

**Comment by lolamtisch** [comment]
Should be fixed in 0.5.1
